### ISSUE TITLE
Made a homebrew script to install chaiscript

### ISSUE THREAD

**Issue by theontho** [ChaiScript/ChaiScript#105]
Feel free to take it and use it for what you want, it's public domain:

Usage:
$ brew tap mahyar/ot
$ brew install chaiscript

It's based off a branch commit, but its what I needed to make the script work for OSX.

https://github.com/mahyar/homebrew-ot

**Comment by No0n3Left** [comment]
[Chaiscript](https://github.com/Homebrew/homebrew-core/blob/master/Formula/chaiscript.rb) has been in homebrews core package list for a while now, so this issue probably can be closed.
