### ISSUE TITLE
Simpler definition of globals in scripts

### ISSUE THREAD

**Issue by kermado** [ChaiScript/ChaiScript#122]
Firstly, thank you for this awesome library!

I see that you allow the definition of global variables from within scripts by using the add_global function. Would it be possible to add a more concise method for defining globals?

Perhaps by omitting the var keyword, similar to JavaScript: `someGlobal = 5`

**Comment by ivandmitrievsky** [comment]
@lefticus, don't do this in a proposed way! It deserves a keyword in **capital** letters.

**Comment by aggsol** [comment]
Maybe `GLOBAL foo = 12;`? Globals could be a way to create namespaces in ChaiScript.

**Comment by lefticus** [comment]
@aggsol I've just committed generic dynamic objects to `develop` that I intend to use as namespaces, basically as you propose.

```
GLOBAL myNamespace = Dynamic_Object();
myNamespace.value1=15;
myNamespace.value2=12;
/// etc
```

Just hadn't decided on `GLOBAL` or `global` yet for this current feature.
