### ISSUE TITLE
Can't compile example or link to chaiscript.

### ISSUE THREAD

**Issue by PhilCK** [ChaiScript/ChaiScript#126]
Hi, 

This might be more down to my ineptitude with the command line but I can't get the example given [here](1) working.

This was the exact command I used.

`clang++ Main.cpp -I./ -ldl -std=c++11 -stdlib=libc++`

Which produces the error.

> chaiscript_engine.hpp:656:16: error: no matching member function for
>       call to 'add'

Also if I try to link to the lib with just an empty main().

`clang++ Main.cpp -o foo -ldl -I./ -L./ -lchaiscript_stdlib-5.3.1 -std=c++11 -stdlib=libc++`

I get the linker error

> ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file './/libchaiscript_stdlib-5.3.1.so' for architecture x86_64

Any ideas?

**Comment by AndrewDavis** [comment]
"but requires that chaiscript be able to find the stdlib at runtime"
How do we ensure that? I would very much like to get rid of this extremely slow compilation. I'm using Visual Studio 2013 Community Edition. None of your examples, documentation, or other help provide any such information on how this works. Thanks.

**Comment by lefticus** [comment]
I'm curious how slow is "extremely slow" in your project.

ChaiScript looks in its current directory and in a directory pointed to by the constructor for its standard lib:

https://github.com/ChaiScript/ChaiScript/blob/develop/include/chaiscript/language/chaiscript_engine.hpp#L465-L466

Which is documented here: http://chaiscript.com/docs/5/classchaiscript_1_1ChaiScript.html#a8e79e489433a52227f05206128e0e4a6 (available from the 'docs' page of http://chaiscript.com)

The problem with loading the standard library from a .dll is that it *must* be compiled with *exactly* the same settings as the rest of the application. This is a limitation of C++.

What I recommend, and use in my own projects, is a system where you have multiple files that each compile a different part of your ChaiScript usage. This leads to very fast (and parallelizable) builds that only rarely have to re-build.

See here: https://github.com/ChaiScript/Spiced

Look at the set of `ChaiScript_*` source files.

**Comment by AndrewDavis** [comment]
Somewhere around a minute for a project that consists of *only* ChaiScript, on a decently fast computer where normally compilation takes at most a few seconds for an empty project. What's really killer about it though is that this happens every time I compile, whether I've changed anything or not.

I'll look into this and get back to you if I can't get it working, thanks.

**Comment by AndrewDavis** [comment]
I can't get it working. I tried chai(vector<string>({ "C:\\Windows\\System32\\" })) (in an initializer list), which is where the standard library DLL is located. Why can't ChaiScript just use stdlib.h? I feel like something like this would be far less murderous of a solution. Also, why does ChaiScript and/or the stdlibrary with it have to recompile every time I run my program in Visual Studio?

**Comment by lefticus** [comment]
I believe you are mistaking ChaiScript's "stdlib" which is ChaiScript's core set of functions with the C++ standard library. The point is that you need to compile ChaiScript's standard library. it would be named something like chaiscript_stdlib-5.7.1.dll

If you are concerned about the longer term maintainability and compile time of a project using ChaiScript, please see the "Spiced" example I linked in the last answer.

**Comment by AndrewDavis** [comment]
Okay, finally got it much faster, thank you. It only takes about 26 seconds now, if I change the code. I placed the DLL in the same directory, and it worked right away without the StdLib. I would really like to be able to link the DLL statically though, as I would like for this to be one portable executable file. Is this possible, and how would I do so?

It was actually originally taking about 85 seconds to compile, by the way, and it didn't seem to change whether I used the DLL or StdLib.

For those who are in my shoes, here's the code I used for Visual Studio Community 2013:

ChaiScriptCreate.h:

#ifndef CHAISCRIPTCREATE
#define CHAISCRIPTCREATE

#include <memory>

using namespace std;

namespace chaiscript
{
	class ChaiScript;
}

unique_ptr<chaiscript::ChaiScript> CreateChaiScript();

#endif


ChaiScriptCreate.cpp:

#include "ChaiScriptCreate.h"
#include "chaiscript\chaiscript.hpp"

using namespace chaiscript;

unique_ptr<ChaiScript> CreateChaiScript()
{
	unique_ptr<ChaiScript> chai = make_unique<ChaiScript>();

	return chai;
}


"Wherever you use it".h:

#include "chaiscript\chaiscript.hpp"
#include "ChaiScriptCreate.h"

using namespace chaiscript;

unique_ptr<ChaiScript> chai;


"Wherever you use it".cpp:

chai = CreateChaiScript();
