### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by lucidguppy** [ChaiScript/ChaiScript#127]
Hi would it be possible for someone from the contributors help me write a tutorial for chaiscipt?  I've tried this morning and I've not really gotten far with it.

I was able to make a module but I don't know how to "import" it and use it.

I would gladly work with someone to do a sort of copy of the python tutorial to chaiscript if anyone is interested.

**Comment by lefticus** [comment]
@lucidguppy I'm curious if you ended up finishing that example / want it added to the official list of examples.

**Comment by lucidguppy** [comment]
I'm sorry - you can drop it.  I haven't given it much thought.

**Comment by lefticus** [comment]
Thanks and no problem
