### ISSUE TITLE
Add traditional for-each loops to ChaiScript

### ISSUE THREAD

**Issue by ebkalderon** [ChaiScript/ChaiScript#145]
As far as I can tell, ChaiScript doesn't appear to support traditional range-based for loops. The existing `for_each(container, fun)` loop works, but requires a bit of extra typing and defining an extra function to feed into it. Ideally, this functionality should be built into the regular for loop, as in JavaScript and Here are some examples of a possible design:

```js
var foo = [1, 2, 3];
for (num, foo) {
    print(num);
}

var foo = [1, 2, 3];
for (num in foo) {
    print(num);
}

var foo = [1, 2, 3];
for (num : foo) {
    print(num);
}

var foo = [1, 2, 3];
for (i, num, foo) {
    print(i.to_string() + ": " + num.to_string());
}
```

The last example above was inspired by Squirrel's for-each loop, which also allows optional access to the index (unsigned int) by specifying an identifier followed by a comma like this:

```lua
local foo = [1, 2, 3];
foreach (i, num in foo) {
    print(i + ": " + num);
}
```

EDIT:
Apparently there is a `for_each(container, fun)` function in ChaiScript. Changed title and post to reflect this.

**Comment by lefticus** [comment]
Additional note: this should contain support for enumeration of the index location like python's enumerate function possibly: https://docs.python.org/2/library/functions.html#enumerate
