### ISSUE TITLE
Local scope for functions

### ISSUE THREAD

**Issue by NoeHedde** [ChaiScript/ChaiScript#153]
I am trying to make a function taht return another function that is using the parameter of the first as a variable but when calling it the variable is unkown.

exemple ;
var f = fun(x) {
return fun(y) {
print(x+y)
}}

f(1)(2)

this is needed for using a function in a for_each.

**Comment by lefticus** [comment]
Use the `bind` function. ChaiScript lambda functions never automatically capture variables.

```
var f = fun(x) {
  return bind(fun(x, y) {
    print(x+y)
  }, x, _);
}

f(1)(2)

```

**Comment by NoeHedde** [comment]
Thank you for the quick answer.
It works
