### ISSUE TITLE
No error reports on assignment to methods

### ISSUE THREAD

**Issue by itagaki-takahiro** [ChaiScript/ChaiScript#154]
Assignments to methods seems to be accepted, but cannot see any effects.
Should errors be thrown in the case?

```
> var abc := "ABC"
ABC
> var n = abc.size = 10
10
> abc.size
3
> n
10
```

**Comment by lefticus** [comment]
Note, this seems to be a general issue with return values not being handled as const. I'm looking into it. As an example:

`to_string(5) = "str"` causes a crash - not good.

**Comment by lefticus** [comment]
See also this note regarding lack of error when assigning to member data: https://gist.github.com/VictorJL/8d9f84f6b4f5ecfd9c63

**Comment by lefticus** [comment]
This has been fixed, and in the process we fixed the extra unexpected copies that occur when constructing an object. Example:

```
var o = MyClass();
```

Used to require a copy constructor, it no longer does.
