### ISSUE TITLE
Direct calls to lambdas doesn't work when store inside objects (+hidden exception)

### ISSUE THREAD

**Issue by WoLfulus** [ChaiScript/ChaiScript#155]
I don't know exactly why this happens, but seems there's a problem when calling lambdas stored inside objects... I thought it was because I was storing it inside a vector of objects, but doing several more tests, this is the result:

First test:

	//
	// Bug
	//

	class MyObject
	{
		var lambda
			def MyObject(lambda)
		{
			this.lambda = lambda
		}
	}

	var myfunction = fun()
	{
		log("log")
	}
	var objects = []
	var object = MyObject(myfunction)
	var func1 = object.lambda
	objects.push_back(object)
	var func2 = objects[0].lambda

	myfunction() // OK
	func1() // OK
	func2() // OK

	(objects[0].lambda)() // Does nothing
	objects[0].lambda() // Does nothing
	(object.lambda)() // Does nothing
	object.lambda() // Does nothing

I then tried adding an argument to the lambda:

	//
	// Bug
	//

	class MyObject
	{
		var lambda
			def MyObject(lambda)
		{
			this.lambda = lambda
		}
	}

	var myfunction = fun(str)
	{
		log(str)
	}
	var objects = []
	var object = MyObject(myfunction)
	var func1 = object.lambda
	objects.push_back(object)
	var func2 = objects[0].lambda

	myfunction("test 1") // OK... outputs test 1
	func1("test 2") // OK... outputs test 2
	func2("test 3") // OK... outputs test 3

	(objects[0].lambda)("test 4") // Fails with an exception
	objects[0].lambda("test 5")
	(object.lambda)("test 6")
	object.lambda("test 7")

The exception thrown is:

	Error: "Error with function dispatch for function 'lambda'" With parameters: (Dynamic_Object).(const string) during evaluation at (..\Data\Scripts\timer.chai 28, 2)
	  Expected: (Dynamic_Object).()
	  ..\Data\Scripts\timer.chai (28, 2) 'objects[0].lambda("test 4")'
	  from ..\Data\Scripts\main.chai (5, 1) 'use("timer.chai")'

This is weird, because on the first test, the function is not called at all, but still no exception is given, and on the second test, the lambda is expecting 0 parameters but the lambda expects one parameter to be passed.

**Comment by lefticus** [comment]
Everything in ChaiScript is a function, even members of objects, that fact is just hidden from the user. So I believe the issue here is that:

    object.lambda() 

Is being handled as "call the function that returns the lambda member value." So, assuming I'm right, I'd expect some version of:

    object.lambda()()

or

    (object.lambda())()

to work. And I'll need to adjust the runtime to handle this particular case.
