### ISSUE TITLE
Problems compiling ChaiScript 5.6 with MSVC2013

### ISSUE THREAD

**Issue by patlecat** [ChaiScript/ChaiScript#159]
I have strange errors when I try to use ChaiScript 5.6 under Windows 8.1-64 with MSVC2013 as the compiler, via QtCreator. Building ChaiScript separately worked well and I could even run the test programs with no error.

I copied the complete **include** folder over to my project and even tried to link with the lib files. But no matter if I link to the lib files or just refer to the headers, I get several of the following errors. What is the matter here?

Those are from the function: *static std::string get_error_message(DWORD t_err)*

```
C:\Development\Qt5\ChaiScripter\chaiscript\include\chaiscript\language\chaiscript_engine.hpp:186: error: C2664: 'DWORD FormatMessageW(DWORD,LPCVOID,DWORD,DWORD,LPWSTR,DWORD,va_list *)' : cannot convert argument 5 from 'StringType' to 'LPWSTR'
Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast

C:\Development\Qt5\ChaiScripter\chaiscript\include\chaiscript\language\chaiscript_engine.hpp:197: error: C2664: 'HMODULE LoadLibraryW(LPCWSTR)' : cannot convert argument 1 from 'const char *' to 'LPCWSTR'
Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

**Comment by patlecat** [comment]
Update: Actually adding the following line to my main.cpp gives me already the errors mentioned above!! :-O I tried to look for some configurations or other additions that could help but couldn't find any. I see that chaiscript_stdlib.hpp is mentioned somewhere in the code as being necessary, but it isn't included through chaiscript.hpp... so not sure what that means, neither do I see what the stl_extra.cpp does.

```
#include <chaiscript/chaiscript.hpp>

**Comment by lefticus** [comment]
It appears as though your configuration is set up for unicode (note the `LoadLibraryW`, which is the unicode version) but the pre-processor define `_UNICODE` expected here: https://github.com/ChaiScript/ChaiScript/blob/develop/include/chaiscript/language/chaiscript_engine.hpp#L169 is not set.

I don't know how it's possible for that to happen. It would appear that QtCreator is doing something that's broken in this regard. I will install it myself and try when I get the chance. 

In the meantime, if you `#define _UNICODE`  **before** including ChaiScript it should work around whatever QtCreator is doing.

**Comment by patlecat** [comment]
@lefticus Ah yes that was it, **great**! Thanks :) Really strange indeed that using a different IDE with the same compiler can produce such huge and unpredictable differences.

BTW I would greatly appreciate some documentation on what means what at the build-stage. Like the stuff I mentioned above that I don't know what to do with, or ignore... or what? (**chaiscript_stdlib.hpp + stl_extra.cpp + threrading**, etc.)

**Comment by lefticus** [comment]
Fixed here https://github.com/ChaiScript/ChaiScript/commit/b71f9db5c2e3527602cf88091c02da20b2eb260c
