### ISSUE TITLE
More Documentation, more examples

### ISSUE THREAD

**Issue by patlecat** [ChaiScript/ChaiScript#160]
As I'm a total beginner in ChaiScript I encounter a lot of small details (and sometimes not so small) that I cannot find any docs for or docs that need updates (like for the keywords where class was added but not documented). Does ChaiScript offer help for syntax highlighting (would be very nice for Qt's [QSyntaxHighlighter](http://doc.qt.io/qt-5/qsyntaxhighlighter.html), and for debugging info?

More or more extensive examples would also be very helpful. Browsing through the scripts I could not find one example with datatypes other than int and string. But how does ChaiScript handle STL containers or Boost or Qt containers or my own? The trivial examples are helpful to get started but for real applications we need a bit more.

**Comment by lefticus** [comment]
Regarding syntax highlighting: vim and geshi support ChaiScript, at the least. If you'd like to take the lead on adding support for QSyntaxHighlighter, let me know, that'd be great.

For documentation:

 1. Note that the unittests show every feature of ChaiScript that exists: https://github.com/ChaiScript/ChaiScript/tree/develop/unittests
 2. The documentation is here, if you did not already find it: http://chaiscript.com/docs/5/
    * Specifically, defining your own types inside of ChaiScript is documented here: http://chaiscript.com/docs/5/LangObjectSystemRef.html
    * Adding your own C++ types to ChaiScript: http://chaiscript.com/docs/5/index.html#adding_items
    * Also look at the test module code for some concrete examples: https://github.com/ChaiScript/ChaiScript/blob/develop/src/test_module.cpp
 3. Lots of discussion is happening on the discourse page where people ask specific questions: http://discourse.chaiscript.com/
    * Particularly this has some more complex script examples http://discourse.chaiscript.com/t/how-to-manage-multiple-scripts/21

ChaiScript works with any objects you throw at it. I don't know what examples you were looking at but many of the unittests use `Vector` (aka std::vector<chaiscript::Boxed_Value>) and `Map` (aka std::map<std::string, chaiscript::Boxed_Value>). Also these examples http://chaiscript.com/examples.html cover some of the details of working with `Function` objects and working with vectors.

**Comment by patlecat** [comment]
@lefticus Thanks for this list, surely helps to know where things are. I have not yet seen a link that was new to me though. That's why I wrote **more** doc and **more** examples :D The documentation is still sparse for users of your language. If I were to contribute to the project, I would join the discourse forum. Forums and unit-tests cannot replace proper documentation though. It would help propagate your interesting language just like the thousands of books did for Java (and the dozens of books for C++ ;) ).

Btw have you ever considered doing some **benchmarks** to measure the real speed of ChaiScript?

**Comment by patlecat** [comment]
Besides, if I decide to use ChaiScript in my application then I will definitely have to write a **QSyntaxHighlighter** class with a very simple editor in my app to make it as easy as possible for users to write scripts.

**Comment by jagoly** [comment]
If you do write a highlighter, please do share it. I've also got a small game editor which will need to edit chai-scripts.

**Comment by patlecat** [comment]
Sorry for the long absence, I got a new job and had no more time for my private projects. But I'll let you guys know if I pick them up again. Thanks to all.
