### ISSUE TITLE
A way to capture variables in lambdas?

### ISSUE THREAD

**Issue by treasurebox** [ChaiScript/ChaiScript#161]
For example:
var b = 4
var add2 = fun(x, y) { x + y + b}

I get: Can not find object: b

I would expect that variables could be captured.

**Comment by lefticus** [comment]
There's no automatic capturing in ChaiScript, use `bind`:

```
var add2 = bind(fun(x,y,b) { x + y + b}, _, _, b)
```

see for examples:

https://github.com/ChaiScript/ChaiScript/blob/develop/unittests/bind.chai

and

https://github.com/ChaiScript/ChaiScript/blob/develop/unittests/bind2.chai

**Comment by treasurebox** [comment]
Thanks for the quick answer. Yeah, that makes sense. Would it be possible to add syntax for something less cumbersome, and more readable (capture list as syntactic sugar) ? Like e.g.:

var add2 = fun[b](x,y) { x+y+b }

**Comment by lefticus** [comment]
That syntax looks probable. Not sure when I'll be able to get it in, though.

**Comment by treasurebox** [comment]
Good to hear that! Keep up the good work :)

**Comment by treasurebox** [comment]
That was quick! Thank You!
