### ISSUE TITLE
Loading stdlib module

### ISSUE THREAD

**Issue by Xandev** [ChaiScript/ChaiScript#163]
Hi, 
How to properly load stdlib module without requirement of lib and/or dll?
Something like that...

    #include <chaiscript/chaiscript.hpp>
    #include <chaiscript/chaiscript_stdlib.hpp>
    int main()
    {
	    chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());
	    return EXIT_SUCCESS;
    }

...throws exceptions in VS2013 community

    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: chaiscript::exception::name_conflict_error at memory location 0x00A8F05C.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: chaiscript::exception::name_conflict_error at memory location 0x00A8F05C.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: chaiscript::exception::name_conflict_error at memory location 0x00A8F05C.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: chaiscript::exception::name_conflict_error at memory location 0x00A8F05C.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: chaiscript::exception::name_conflict_error at memory location 0x00A8F05C.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: std::range_error at memory location 0x00A8DE68.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: std::range_error at memory location 0x00A8DE68.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: std::range_error at memory location 0x00A8DE68.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: std::range_error at memory location 0x00A8DE68.
    First-chance exception at 0x7767C42D in heap_allocated_chaiscript_test.exe: Microsoft C++ exception: std::range_error at memory location 0x00A8DE68.

I've tried master and develop branch. Any advice?

**Comment by lefticus** [comment]
Those exceptions are all handled internally and they do not affect your code. Everything is working properly.

**Comment by lefticus** [comment]
see also: https://github.com/ChaiScript/ChaiScript/issues/158

It's a to-do item to see if we can reduce those. But they have virtually no affect on you.
