### ISSUE TITLE
Support floating point literals using scientific notation

### ISSUE THREAD

**Issue by totalgee** [ChaiScript/ChaiScript#173]
ChaiScript seems not to accept floating point numbers of the form `3e8`, `-1.47e-200`, etc.  It would be helpful if it did.  It doesn't necessarily have to support *all* the C++ parsing possibilities -- e.g. potentially it could require 3.0e8 (with decimal and following number) rather than just 3e8, doesn't need to support upper-case 'E', etc.

Right now, if you calculate a very large or small number and use print(), they show up in scientific notation.  But if you take those same results as strings and paste them into a script, they're not recognized.

    print(1000000.0 * 1000000)
    // --> 1e+12
    print(1.0 / 12345)
    // --> 8.10045e-05
    print(1e+12 / 8.10045e-05)
    // --> exception thrown...

I think a regex like the following should work to recognize floating point numbers, which can then be converted to numbers using std::stof() as you do now:

    [-+]?\d*\.?\d+(e[-+]?\d+)?

I took a quick look at the parsing in chaiscript_parser.hpp, and it's not using regexes, but rather its own kind of state machine.  I'll take a look and maybe send a pull request.

**Comment by lefticus** [comment]
That's correct that we don't currently use any regex. I think all of the platforms we support right now (finally) have std::regex support available, but we were not going to add an external dependency for it.

Somewhere between these lines you'd need to detect the 'e' or 'E' optional '-' or '+' then another set of collecting up integers: 

https://github.com/ChaiScript/ChaiScript/blob/develop/include/chaiscript/language/chaiscript_parser.hpp#L439-L442

-Jason

**Comment by totalgee** [comment]
This has been resolved by my pull request #174 and merged by Jason.  Closing.
