### ISSUE TITLE
Support switch statements

### ISSUE THREAD

**Issue by lefticus** [ChaiScript/ChaiScript#18]
Allow the following:

```
switch (myvalue)
{
   case 1:
     // do something
     break;
   case 2:
     // do something else
    break;
};
```

To be consistent with C++, this would require support for labels and break statements. The labels can be emulated, but the break statements and fall through would have to actually be supported.

**Comment by pmthompson** [comment]
I'm sure this is obvious to everyone else, but without the "break" statement, each "case" handler will fall through to the ones after.
