### ISSUE TITLE
ChaiScript has an "odd" license; adopt a standard OSS license

### ISSUE THREAD

**Issue by LegalizeAdulthood** [ChaiScript/ChaiScript#181]
Because ChaiScript uses a one-off license, it slows the adoption for use in commercial products.  The one-off license must be reviewed by the legal counsel in each firm before ChaiScript can be readily used.  If ChaiScript used a [more standard license[(http://opensource.org/licenses) that allowed commercial use, such as the MIT License, Boost, Apache, etc., then ChaiScript could be more readily incorporated into commercial products without special legal consultation.

**Comment by lefticus** [comment]
ChaiScript uses the BSD license, with our names simply filled in. From the link you provided: http://opensource.org/licenses/BSD-3-Clause and our  license: https://github.com/ChaiScript/ChaiScript/blob/develop/license.txt

**Comment by LegalizeAdulthood** [comment]
Gah.... I feel stupid now for missing that.  Thanks for pointing me to it!
