### ISSUE TITLE
filter() does not work with Range and Map

### ISSUE THREAD

**Issue by nxtruong** [ChaiScript/ChaiScript#183]
`filter()` works with Vector, e.g. `filter([1, 2, 3], odd)`, but does not work with `Range`. For example
``filter([1, 2, 3].range(), odd)` fails with `Error: "Function dispatch arity mismatch with function ''" during evaluation at (29, 3)`

Furthermore, `filter()` does not work with `Map`. For example
> var m = ["a": true, "b": false, "c": true];
> filter(m, fun(p) {p.second();})

causes error `Error: "Error with function dispatch with function 'inserter'" With parameters: (Map, Map_Pair) during evaluation at (400, 7)` while
> filter(m.range(), fun(p) {p.second();})

causes the same error as with Vector.

**Comment by lefticus** [comment]
`filter` is implemented by creating a new container of the type passed in, and filling it with the filtered values, then returning the new container.

This makes it impossible for it to work with `Range` but could work with `Map` if we provide an `inserter` function.

I'll look into that, but I'm guessing that what you really want is something like lazy evaluation or list comprehensions. ChaiScript doesn't currently support generators or continuations which makes both of those options not as good as they could be.

You could certainly write your own functions that return a new range-like object that contains the passed in range and filters on each call to `pop()`. If you develop anything like that, please share it.

**Comment by nxtruong** [comment]
The document (http://chaiscript.com/docs/5/namespaceChaiScript__Language.html#a9ad6e8cb9f73133ad596f050c8fd567b) says `filter` accepts a `Range` object. Perhaps you should change the document.
