### ISSUE TITLE
In-place map object cannot look up entries

### ISSUE THREAD

**Issue by nxtruong** [ChaiScript/ChaiScript#184]
I'm using version 5.7.0.
Define a simple function:
> def f(Map m) { print(m["a"]); }

It works properly on a Map variable like this:
> var m = ["a" : 1, "b" : 2]
> f(m) // prints 1

However, if it's called with an in-place Map object, like this:
> f(["a" : 1, "b" : 2])

it causes an error: `Error: "Can not find appropriate array lookup operator '[]'." With parameters: (const Map, const string) during evaluation at (1, 19)`.

**Comment by lefticus** [comment]
This is because ChaiScript's map is implemented with `std::map<std::string, Boxed_Value>`. So, just like in c++, there is no const version of `operator::[]`.

However, it probably does make sense to add a const version that simply throws if the value doesn't exist. I'll look into that shortly.

**Comment by nxtruong** [comment]
May it be useful to have the `at` method included? The drawback is that it requires C++11.

**Comment by lefticus** [comment]
I've required C++11 for a very long time (variadic templates for deducing function types). But I did not realize the `.at` method had been added. Thank you for bringing it up. I will do that.
