### ISSUE TITLE
Performance Comparisons

### ISSUE THREAD

**Issue by BianJian** [ChaiScript/ChaiScript#189]
Hi, I like chai, I tested the performance  about chaiscript  and lua , the result was sad. chaiscript was too slow, is anything I can do to improve chaiscript performance  or just not to worry about this ?

chaiscript sum time :   4.73 sec
lua sum time: 0.36 sec

chai prime time:  31.01 sec
lua  prime time:  0.35  sec

windows 7 64  AMD Phenom(tm) 8650 
chaiscript : ver 5.7.0  
lua:  ver 5.1

The BAT file:
```
@echo %time%
@D:\project\ChaiScript-5.7.0\build\MinSizeRel\chai.exe sum.chai
@echo %time%
@pause
```

chai  sum test code:

```
var sum = 0.0
for (var i = 1; i <= 100000; ++i) {
	if (i % 2 == 0) {
		sum += 1.0 / i;
	}
	else {
		sum += 1.0 / (double(i) * i);
	}
}
```

lua  sum test code:

```
sum = 0.0
for i = 1, 100000 do
    if i % 2 == 0 then
        sum = sum + (1.0 / i)
    else
        sum = sum + (1.0 / (i * i))
    end
end
```

chai prime test code:
```
def isprime(n)
{
  for (var i = 2; i < n; ++i)
  {
    if (n % i == 0) {return false}
  }

  return true
}


def primes(n)
{
  var count = 0
  for (var i = 2; i <= n; ++i)
  {
    if (isprime(i)) {++count}
  }

  return count
}


var N = 5000

print("primes: " + primes(N).to_string())
```

lua prime test code:

```
function isprime(n)
    for i = 2, (n - 1) do
        if (n % i == 0) then
            return false
        end
    end
    return true
end


function primes(n)
    local count = 0

    for i = 2, n do
        if (isprime(i)) then
            count = count + 1
        end
    end
    return count
end


N = 5000
print("primes: " .. primes(N))
```

**Comment by lefticus** [comment]
I've never seen a build of ChaiScript go that slow. I'm not sure how that would be possible.

To get the most performance:

* Don't do a "MinSize" build, do a regular "Release" build
* Set `-DCHAISCRIPT_NO_THREADS` ChaiScript is by default thread safe, and Lua is not, if you want to compare it to Lua, disable thread safety
* Try the current `develop` branch. It has many performance enhancements on it

With these settings on Linux with g++, I get the 'primes' test to only .75s

Arguably, if you are using your script engine (any engine) to calculate primes, you are using scripting wrong. Put all of the performance critical functions inside of C++ and call those from your script engine.

* ChaiScript excels at calling C++ functions, not at math. Compare the # of lines of code and performance of Lua for calling C++ functions to ChaiScript.

Finally:

* ChaiScript will never be as fast as Lua or JavaScript at math. Its primary design goal is to make scripting natural, easy, and flexible. By comparison Lua is very rigid and they are able to make many more performance optimizations.

**Comment by lefticus** [comment]
@BianJian I just did some more testing and see that VisualStudio 2015 produces executables that are 2-3x faster than 2013. This is mostly due to the limitations of VS 2013 - it doesn't support enough of C++11 to get the best performance possible.

**Comment by BianJian** [comment]
thx, according to your advice, I tested  on
windows 7 64 AMD Phenom(tm) 8650
vs 2013 update 4

chaiscript 5.7       primes test :  9.43 sec
charscript develop primes test : 6.67 sec;
tomorrow  I will test on my centos  in my working place.

**Comment by BianJian** [comment]
as your advice, I tested on centos7  gcc 4,8.3, but that's  an error in your CMakeLists.txt:
if(MINGW OR CYGWIN)
  add_definitions(-O3)
endif()
after I  del  the if condition, the test was almost as fast as  your said.

And I  tested  the cost of invoking cpp function vs lua.
invoke times:  20000000
chai (windos7 64  vs2013 update 4)    115.02 sec
chai( centos 7 64 vmware)    37.995 sec
lua (windows 7 64 5.1.3)   2.22 sec


chai test file:
 cpp  source:

std::string average(
const std::string a1, const std::string a2, const std::string a3,
 const std::string a4, const std::string a5, const std::string a6, 
const std::string a7, const std::string a8, const std::string a9,
 const std::string a10)
{
    std::string sum = a10;
    return sum;
}

chai source:

def primes(n, a1, a2, a3, a4, a5, a6, a7, a8, a9)
{
	var sum;
  for (var i = 0; i <= n; ++i)
  {
    sum = average(a1, a2, a3, a4, a5, a6, a7, a8, a9, "hah")
  }
  return sum;
}

var N = 20000000
var a1 = "1";
var a2 = "1";
var a3 = "1";
var a4 = "1";
var a5 = "1";
var a6 = "1";
var a7 = "1";
var a8 = "1";
var a9 = "1";
primes(N, a1, a2, a3, a4, a5, a6, a7, a8, a9)


lua test files:

cpp source:
int average(lua_State *L)
{
	int n = lua_gettop(L);
	lua_pushstring(L, lua_tostring(L, 10));
	return 1;
}

lua source:

function primes(n, a1, a2, a3, a4, a5, a6, a7, a8, a9)
	local sum;
    for i = 0, n do
        sum = average(a1, a2, a3, a4, a5, a6, a7, a8, a9, "hah")
    end
	return sum;
end


N = 20000000
a1 = "1";
a2 = "1";
a3 = "1";
a4 = "1";
a5 = "1";
a6 = "1";
a7 = "1";
a8 = "1";
a9 = "1";
local sum = primes(N, a1, a2, a3, a4, a5, a6, a7, a8, a9)


I m confused , how to use chai. whats the best way of using chai with cpp  ?
in server side, the performance is important.

**Comment by lefticus** [comment]
There is not a bug in the `CMakeLists.txt` file. You have to choose "Release" build to get it to build with `-O3`. The code you referenced is because mingw has a bug in it and ChaiScript *must* be built with optimizations to build at all.

Part of the problem is that you are copying 200,000,000 strings in the ChaiScript version, but none at all in the Lua version.

You can get a minor performance improvement (~10%) by passing those strings as `const std::string &` instead of `const std::string`.

Otherwise, you still aren't really comparing the same things. In the Lua version you never attempt to actually access the first 9 strings from C++. Nor do you attempt to access the content of the string at all as a C++ string.

There's not much else I can tell you. Either the ease of working with ChaiScript and its integration with C++ is worth it to you, or it is not. We try to have good performing code (ChaiScript today is almost 100x faster than ChaiScript 1.0), Lua is much older, less flexible, harder to integrate with C++, and has had many more people working on optimizing it.
