### ISSUE TITLE
Incomplete class block

### ISSUE THREAD

**Issue by PhilCK** [ChaiScript/ChaiScript#197]
Was testing out Chai's class features but I couldn't get the class [example](https://gist.github.com/lefticus/ab997fec9decf043e0b3#file-chaiscript_oop-chai) working. So I removed as much as I could and it comes down to `var data` member var. Am I doing something wrong? (On current master branch).

### Error
```
$ clang++ test.cpp -ldl -std=c++11 -I./ && ./a.out
libc++abi.dylib: terminating with uncaught exception of type chaiscript::exception::eval_error: Error: "Incomplete class block" during evaluation  at (1, 27)
Abort trap: 6
```

### Platform
```
$ clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

### Test Code 
```cpp
#include <chaiscript/chaiscript.hpp>
 
std::string helloWorld(const std::string &t_name)
{
  return "Hello " + t_name + "!";
}
 
int main()
{
  chaiscript::ChaiScript chai;
  chai.add(chaiscript::fun(&helloWorld), 
           "helloWorld");

  chai.eval(
"class MyClass"
"{"
"var data" //*** REMOVE THIS AND IT COMPILES AND RUNS *** //
  "def MyClass(x)"
  "{"
    "puts(helloWorld(\"Bob\"));"
  "}"
"}"
"var obj = MyClass(10)"
    );
}
```

**Comment by lefticus** [comment]
Bad C++. You don't have any kind of break at all between your var and your def.

The C++ compiler sees what you typed in as:

```
class MyClass{var datadef MyClass(x){puts(helloWorld("Bob"));}}var obj = MyClass(10)
```

You can explicitly add `\n` line endings at the end of each line or you can use C++ raw string literals. (demonstrated here: http://discourse.chaiscript.com/t/how-to-manage-multiple-scripts/21/4?u=lefticus) your choice.

**Comment by PhilCK** [comment]
right you are. I added `;` and it worked. Thanks.
