### ISSUE TITLE
Fix warning for WIN32_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by msbroadf** [ChaiScript/ChaiScript#202]
I already declare WIN32_LEAN_AND_MEAN elsewhere and the compiler complains about redefinition when building chaiscript,  I add this to workaround in chaiscript_engine so it compiles cleanly, 

#if !defined(WIN32_LEAN_AND_MEAN)
#define WIN32_LEAN_AND_MEAN
#endif

Could you add that as a patch

**Comment by lefticus** [comment]
Would you mind making it as a pull request here on github?

**Comment by msbroadf** [comment]
Im not sure how to do that, i just downloaded chaiscript via the zip file on github and then copied it to my project. Is there some way to create a pull request without checking in a whole new branch to github?  I clicked "New Pull Request" on their website but it wants a branch to create the pull request...

**Comment by lefticus** [comment]
* From here: https://github.com/ChaiScript/ChaiScript Click on the "fork" button, this will create a fork of ChaiScript under your account
 * Make the changes you are suggesting (you can do this from within the web interface, the file should now be available at: https://github.com/msbroadf/ChaiScript/blob/develop/include/chaiscript/language/chaiscript_engine.hpp#L39 after you make the fork)
 * Then create a new pull request from your fork's page https://github.com/msbroadf/ChaiScript/pulls

**Comment by msbroadf** [comment]
Great, done thanks for the info, this will be useful in the future, i use chaiscript in my company product and it works pretty well.

**Comment by lefticus** [comment]
Glad to hear it. Feel free to promote your product on this forum http://discourse.chaiscript.com/t/project-announcements/28
