### ISSUE TITLE
Suggestion: in-place creation compatible with JSON

### ISSUE THREAD

**Issue by nxtruong** [ChaiScript/ChaiScript#207]
Currently, in-place object creation uses the [] pair to create maps, e.g. `["id": 1, "name": "John"]`. Is it possible to change the mark-up pair to {} (or support both)?. So `{"id": 1, "name": "John"}` produces the same object.

The reason I am asking for this change is to make the syntax compatible with a subset of JSON. With this, we can receive a JSON message in a string, pass it to Chaiscript and get a Chaiscript object of the JSON message. Just a suggestion.

**Comment by lefticus** [comment]
Would it also work to just provide a JSON parser that you can call on demand, and it returns a ChaiScript object? This is something I'm strongly considering.

**Comment by nxtruong** [comment]
That would be perfect. I would love to have JSON support in Chaiscript, but thought it would be quite some work. My previous suggestion seemed to be a simple change to partially achieve that, IMHO :-) Do you think we can have JSON support in the next major release? (so that I can plan my project accordingly).

**Comment by lefticus** [comment]
I will attempt to get to this in the near future, but cannot guarantee anything for a few weeks.

**Comment by lefticus** [comment]
I do have working to/from JSON support on a branch right now. I'm going to add some tests then merge it in with develop. https://github.com/ChaiScript/ChaiScript/tree/add_json_support

**Comment by lefticus** [comment]
@nxtruong JSON support now pushed to develop. There are new `from_json` and `to_json` functions
