### ISSUE TITLE
"bad any cast" with Qt's quint32/64 data type

### ISSUE THREAD

**Issue by define-private-public** [ChaiScript/ChaiScript#208]
I'm toying around with integrating ChaiScript into my Qt applications.   When I have a function (in C++) that has Qt's `quint64` data type which is just a `unsigned long long int`, `ChaiScript::eval()` will throw an error with the message "bad any cast."  But if I try to access a method that returns a `quint32/64`, the result is just fine.  e.g.:

```C++
void Class::yolo(quint64 i) {
    cout << (i * i) << endl; 
}

quint64 Class::swag() {
    return 14;
}

//...

Class c;
chai.add(var(&c), "c");
```

```ChaiScript
> c.yolo(20)
bad any cast
> print(c.swag())
14
```

Now let's saw I replace the parameter `i`'s type with `int`, it works just fine and `c.yolo(20)` would return `400`.  Even replacing `quint64` with `unsigned long long int` gives me the `bad any cast`.

**Comment by define-private-public** [comment]
Also, I really like ChaiScript so far.  Top notch stuff.

**Comment by lefticus** [comment]
I have a hunch that the bad any_cast is your attempt to print a `void`

```
print(c.yolo(20)); // yolo returns void
```

Otherwise I cannot think of why there would be an error passing a quint64 vs returning it.

Please verify if that is the issue and verify which version of ChaiScript you are using.

Thanks!

**Comment by define-private-public** [comment]
Hi,

sorry, that `print(c.yolo(20))` was an accident.  I tried it again without the `print()` and I got the same `bad any cast`.  I'm using ChaiScript 5.7.1.

**Comment by lefticus** [comment]
OK, I'll see what I can find.

What compiler / config (64bit/32) / Qt version are you using?

In the meantime, if you need a workaround, something like this REALLY should work (if not that I guess it gives me a clue for where the problem is):

```
chai.add(chaiscript::fun([](Class &o, uint64_t i){ o.yolo(i); }), "yolo");
```

Just creating a simple lambda wrapper around the function call until I figure out what is going on.

**Comment by define-private-public** [comment]
That work around works.

I'm using clang++ to compile (64 bit I think), and Qt 5.4.1

**Comment by lefticus** [comment]
Ok, just FYI, I can easily reproduce this with a parameter that is simply unsigned long long. It should be a relatively easy fix.

**Comment by lefticus** [comment]
I personally use `uint64_t` and `int64_t` for large integer types, which I know work, so I had not looked at the `long long`s

**Comment by define-private-public** [comment]
You also might want to verify some of the other datatypes that Qt has `typedef`d:  http://doc.qt.io/qt-5/qtglobal.html
