### ISSUE TITLE
implicit type conversions

### ISSUE THREAD

**Issue by define-private-public** [ChaiScript/ChaiScript#209]
I was binding a function that took one argument as a double (e.g. `foo(double x)`).  I tried calling it in chaiscript, once passing in an integer and once with a double.  It broke on the integer, but was okay on the double call.

```chaiscript
> foo(2)
Error
> foo(2.0)
<good_things>
```

Is there anything else I could use (other than a lambda function) to do an implicit type conversion in ChaiScript?

**Comment by lefticus** [comment]
Hmm, implicit type conversions between arithmetic types was implemented many versions ago. There must be something else going on.

Please provide a complete example for me to test.

**Comment by define-private-public** [comment]
I should have clarified, it was happening when I was using the `/=` operator.  Here's some code that will reproduce the error.

```c++
#include <iostream>
#include <string>
#include <chaiscript/chaiscript.hpp>
#include <chaiscript/chaiscript_stdlib.hpp>
#include <chaiscript/utility/utility.hpp>
using namespace std;
using namespace chaiscript;
using namespace chaiscript::utility;


class Point {
public:
	double x, y;

	Point() : x(0), y(0) { }
	Point(int x_, int y_) : x(x_), y(y_) { }

	string str() { return "(" + to_string(x) + ", " + to_string(y) + ")"; }

	Point divide(double div) {
		return Point(x / div, y / div);
	}

	Point &operator/=(double div) {
		x /= div;
		y /= div;
		return *this;
	}

};


int main() {
	ChaiScript chai(Std_Lib::library());
	ModulePtr m(new Module());

	add_class<Point>(*m,
		"Point",
		{
			constructor<Point()>(),
			constructor<Point(double, double)>(),
		},
		{
			{ fun(&Point::str), "to_string" },
			{ fun(&Point::x), "x" },
			{ fun(&Point::y), "y" },
			{ fun(&Point::divide), "divide" },
			{ fun(&Point::operator/=), "/=" }
		}
	);

	chai.add(m);


	try {
		string cmd[] = {
			"var p = Point(6.2, 4.5);",
			"print(p.divide(2.0));",
			"print(p.divide(2));",
			"print(p /= 2.0);",
			"print(p /= 2);",
		};
		
		for (int i = 0; i < 5; i++) {
			cout << i << ">  " << cmd[i] << endl;
			chai(cmd[i]);
		}
	} catch (std::exception &ex) {
		cout << ex.what() << endl;
	}

	return 0;
}
```

compiled with `$ clang++ test.cpp -std=c++11 -ldl -lpthread`

output:
```
0> var p = Point(6.2, 4.5);
1> print(p.divide(2.0));
(3.000000, 2.000000)
2> print(p.divide(2));
(3.000000, 2.000000)
3> print(p /= 2.0);
(3.000000, 2.000000)
4> print(p /= 2);
Error: "Unable to find appropriate'/=' operator." With parameters: (Point, const int)
```

**Comment by lefticus** [comment]
Ok. I'm still surprised, but slightly less so. operator overloads are a different code path, but they ultimately end up calling the same code.

**Comment by lefticus** [comment]
I'm able to verify the issue with a simple version defined inside of ChaiScript.

```
eval> def string::`/=`(double d) { this = "${this}/=${d}"; return this; }
eval> var s = "hello"
hello
eval> s /= 2
Error: "Unable to find appropriate'/=' operator." With parameters: (string, const int) during evaluation at (1, 1)
eval> s /= 2.0
hellow/=2
```

**Comment by define-private-public** [comment]
This is also happening for `*=`.

**Comment by define-private-public** [comment]
I also have some overloads for the `*` and `/` operators where the parameters are `(Point, double)` or vice-versa.  The function call works if I supply a floating point in chai, but if I supply an integer I get the same style of error.

**Comment by lefticus** [comment]
A slight bug in the overload resolution was causing the runtime to think the function call was ambiguous with the built in Number / Number functions.
