### ISSUE TITLE
postfix increment operator

### ISSUE THREAD

**Issue by define-private-public** [ChaiScript/ChaiScript#210]
Does ChaiScript support the postifx `++` operator?  I tried:
```chaiscript
eval> var i = 2;
2
eval> ++i;  
3
eval> i++;
Error: "Incomplete prefix '++' expression" during evaluation  at (1, 4)
eval> i
3
eval> 
```

**Comment by lefticus** [comment]
It does not. It's kind of a pain to implement, and even in C++ it comes across as a hack.

```
MyType &MyType::operator++(); // prefix
MyType MyType::operator++(int); // postfix - this extra int parameter feels so arbitrary
```

For this reason, we've never implemented it in ChaiScript, but there is an existing issue that I might some day get to.

Closing as duplicate of #143

**Comment by define-private-public** [comment]
Okay, that makes sense.

Can I propose getting rid of the `++` and `--` operators then?  The same thing can be achieved using `+=` and `-=` which ChaiScript already supports.  It seems odd to support prefix, but to not have postfix.
