### ISSUE TITLE
Dynamic memory & Chaiscript

### ISSUE THREAD

**Issue by define-private-public** [ChaiScript/ChaiScript#214]
When I have ChaiScript create a new instance of a class that I defined in C++, how is memory cleanup handled?  So say I have a `Sprite` class that is instantiated inside of ChaiScript, when will that be cleaned up?

That class itself has some OpenGL resources I should be cleaning up when my OpenGLContext is being destroyed.  Right now the sprites are being destroyed when my application exits, but it's not properly cleaning up the OpenGL resources.  I tried to put a `delete` statement to destroy them when my context is being destroyed, but that caused a double free issue.

**Comment by lefticus** [comment]
Objects in ChaiScript have very well defined lifetimes.

If you create something at the top level, it is going to be deleted when the ChaiScript engine is deleted:

```cpp
chai.eval("var o = Object()"); // o is deleted whenever `chai` is destructed
```

ChaiScript respects scoped objects in the same way that C++ does (I believe it is the only non C++ language where this is true and I'm almost positive it's the only scripting language)

```cpp
chai.eval("{ var o = Object(); }"); // o is deleted when the closing } is evaluated
```

It is possible to extend the lifetime of objects by grabbing a copy of the containing `shared_ptr`

```cpp
std::shared_ptr<Object> chaio;

{ //create a new scope for demonstration purposes
  chaiscript::ChaiScript chai;
  chai.eval("var o = Object();");
  chaio = chai.eval<std::shared_ptr<Object>>(o);
} // at the close of this scope chai is destroyed, but o lives on since we grabbed its shared_ptr
```

So, if I understand your question, you need to be able to control exactly when some top level objects are destroyed, or at the very least it needs to be *before* you destroy your OpenGLContext.

From the C++ side, you could use RAII to help, for example:

```cpp
OpenGLContextHolder ogl;
chaiscript::ChaiScript chai;

// do a bunch of work
```

With the above dummy code, C++ guarantees that objects are always destroyed in the opposite order they were created. So you will know that the ChaiScript object and everything it owns is destructed before your object that controls the OpenGLContext is destructed.

From the ChaiScript side, you can manually clear out the local variables by resetting the state of the engine:

```cpp
chaiscript::ChaiScript  chai;
chaiscript::State original_state = chai.get_state();

// do a bunch of stuff with chaiscript

chai.set_state(original_state); // wipe out anything I've done, therefore destructing all globals/locals
```

Or an even more nuclear approach:

```cpp
chaiscript::ChaiScript  chai;
// do stuff
chai.set_state(chaiscript::State()); // not even the original stdlib state is left over
```

There are many other options as well, like grabbing a copy of the local objects with `auto locals = chai.get_locals(); chai.set_state(chaiscript::State());`. At this point you own all of the locals that were created then `locals.clear()` when you want them to be destructed.

I hope that's at least as much information as you wanted.

**Comment by define-private-public** [comment]
This is a good answer, you should add this to the documentation somewhere.

**Comment by lefticus** [comment]
I added a link back to this from the discourse site.
