### ISSUE TITLE
false != true

### ISSUE THREAD

**Issue by define-private-public** [ChaiScript/ChaiScript#217]
I toyed around with the boolean operators a bit.  This came up

```chaiscript
eval> true == true;
true
eval> false == false;
true
eval> false == true;
false
eval> true == false;
false
eval> false != true;
Error: "Can not find appropriate '!=' operator." With parameters: (const bool, const bool) during evaluation at (1, 1)
eval> true != false;
Error: "Can not find appropriate '!=' operator." With parameters: (const bool, const bool) during evaluation at (1, 1)
```

Shouldn't `false != true` return `true` instead of throwing an error?

**Comment by lefticus** [comment]
Good catch. Are there any other boolean comparison operations I might have missed? I cannot think of any others.

**Comment by define-private-public** [comment]
Not sure, I can check later.  In ChaiScript, is `false == 0` and `true != 0` like in C?

**Comment by lefticus** [comment]
That's the one thing I'm explicitly doing differently from C and C++: I've made bool more strongly typed so it does not automatically promote to integer.

**Comment by define-private-public** [comment]
It also might be a good idea to write some unit tests for the boolean operators like `&&`, `||`, and `!`.  Also, does ChaiScript support the bitwise operators?
