### ISSUE TITLE
Suggestion: `GLOBAL` -> `global`

### ISSUE THREAD

**Issue by define-private-public** [ChaiScript/ChaiScript#221]
I don't see why the keyword to declare a global variable needs to be screamed in my code.  I understand the global variables are considered bad practice in some cases (even though they are necessary), and you want to mark them as such, but I think just having the lowercase word `global` in front of a variable name is just fine.

**Comment by define-private-public** [comment]
Thanks for doing this!  Just as another idea, is it possible to deprecate the uppercase `GLOBAL` in a future version too?  as it might be odd to see people using both in one project in the far-far future.

**Comment by lefticus** [comment]
If you want to create another task I might deprecate it when I release 6.0
