### ISSUE TITLE
How to bind a non static class member function to chai?

### ISSUE THREAD

**Issue by hackthehackerman** [ChaiScript/ChaiScript#224]
Hello! Thank you for the work on ChatScript, it's super useful!

I am wondering if anyone could help me with my problem binding a non static class member function to chai? In my project I am trying to call a non static function from chai but it always give me this error:
> Error: "Function dispatch arity mismatch with function 'test1'" )

Here is the code snippet in my program:

```
header:
class NiceClass{
  public:
  static void staticFunction();
  void nonStaticFunction();
}

cpp:
void NiceClass::staticFunction() {printf("hello chai");}

void NiceClass::nonStaticFunction() { printf("goodbye chai"); };

int main{
    chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());
    chai.add(chaiscript::fun(&NiceClass::staticFunction), "staticTest");
    chai.add(chaiscript::fun(&NiceClass::nonStaticFunction), "nonStaticTest");

    chai.eval("staticTest();"); // this will work
    chai.eval("nonStaticTest();"); // this won't work
}
```

Am I not using chai correctly? I will really appreciate any help!

Thank you!

**Comment by lefticus** [comment]
You need an object to call on that function, just like in C++.

```
chai.add(chaiscript::var(&someObject), "someObject");
chai.eval("someObject.nonStaticTest()");
```

**Comment by hackthehackerman** [comment]
Thank you @lefticus !

**Comment by lefticus** [comment]
Here's one more piece of info about bound vs unbound member function calls https://github.com/ChaiScript/ChaiScript/issues/128#issuecomment-52424741

Also, you can probably find more info on http://discourse.chaiscript.com/ for general usage questions.

**Comment by hackthehackerman** [comment]
thank you so much!
