### ISSUE TITLE
std::to_string, std::stoi, std::stol etc are not supported in android build

### ISSUE THREAD

**Issue by yushli** [ChaiScript/ChaiScript#226]
Hi, Is ChaiScript support android platform? When adding ChaiScript to the android project, it reports std::to_string, std::stoi, std::stol etc are not defined in namespace std.

**Comment by lefticus** [comment]
I know other users have used it successfully. It sounds like it's missing the standard library from c++11. 

This stackoverflow answer seems to be what you need: http://stackoverflow.com/questions/22774009/android-ndk-stdto-string-support

You need to use lib-llvmc++ to get it all working, or perhaps upgrade your ndk?

**Comment by yushli** [comment]
Thanks for the reply. I will try to fix that.
