### ISSUE TITLE
Struct constructor

### ISSUE THREAD

**Issue by AaronShea** [ChaiScript/ChaiScript#227]
Hello!

I'm very excited about using Chaiscript in my side game engine project.
But I seem to have run into a wall, I'm using Box2d for physics, and I want to register the b2Vec2 struct with Chaiscript so I can manipulate physics bodies.

Here's my C++

```C++
	engine->add(chaiscript::user_type<b2Vec2>(), "b2Vec2");
	engine->add(chaiscript::constructor<b2Vec2()>(), "b2Vec2");
	engine->add(chaiscript::constructor<b2Vec2 (const float32&, const float32&)>(), "b2Vec2");
	engine->add(chaiscript::fun(&b2Vec2::x), "x");
	engine->add(chaiscript::fun(&b2Vec2::y), "y");
```

and my ChaiScript

```
var testb2Vector = b2Vec2();
```

When I try and eval that script, I get thrown a `chaiscript::detail::exception::bad_any_cast` exception.

Maybe I'm missing something here?

Thanks!

**Comment by lefticus** [comment]
That's very surprising. Can you verify what version you are using and maybe provide a more complete example?

Thanks

**Comment by AaronShea** [comment]
I just realized that this was my own silly fault, I had left something farther down the script that caused the error.

Is there any way to get better error reporting, like line number reporting maybe?

**Comment by lefticus** [comment]
For parse / eval errors, you can catch them by following the model in main.cpp: https://github.com/ChaiScript/ChaiScript/blob/develop/src/main.cpp#L238-L248

For user originated exceptions, there's no way to catch what line it occurred on - and I'm not even sure that would be possible as I would need to modify the exception being thrown. Plausibly could do it with one of the newer C++11 inner exception wrapper things. It's an idea to ponder.
