### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by jespa007** [ChaiScript/ChaiScript#229]
Hi there,

I recently did this test,

```
for(var i=0; i < 100000; ++i){
	
}
```

And I analysed that this takes 1,75us per instruction that means that the performance is 0.5 MIPS more or less like a any computer from the 1977.
Is there any plan to improve that performance? Nowadays we have a powerful  machines, I know that script code there's nothing to compare with machine code but I think that I could be improved a lot. I will investigate in that.

**Comment by jespa007** [comment]
The test was made with system,

![image](https://cloud.githubusercontent.com/assets/7852409/11622939/8c6e37ee-9cc9-11e5-9f24-e64ae6ce1359.png)

**Comment by jespa007** [comment]
It seems there's no virtual machine embedded inside. It could be consider to have a fast script execution if Chaiscript changes the core and implements a virtual machine to let execute byte code.

**Comment by lefticus** [comment]
ChaiScript is highly optimized for C++ function callbacks. I believe at this point if you were to compare ChaiScript to any other embedded scripting environment where you are offloading all of the heavy work back to C++ you will find that ChaiScript is the fastest in that use case.

The point of ChaiScript is that it is so easy to add C++ functions to ChaiScript, and so easy to call them from ChaiScript, that any code that is performance critical should be written in C++ and called from ChaiScript.

Also, each performance is something that is actively being worked on with each release, to make the callback performance as good as it can be.

If you have any patches that increase performance (while maintaining all tests passing) please submit them.
