### ISSUE TITLE
Creating new script engine returns "failed to load module stdlib" error.

### ISSUE THREAD

**Issue by kxait** [ChaiScript/ChaiScript#231]
this:
```interface = new chaiscript::ChaiScript();```
puts me at chaiscript_engine.hpp line 794 which reads:
```throw chaiscript::exception::load_module_error("Unable to find module: " + t_module_name + " Errors: " + errstring);```
where t_module_name is ```chaiscript_stdlib-5.7.1```
i'm using the 5.7.1 with only ```#include "chaiscript\chaiscript.hpp"```

**Comment by lefticus** [comment]
Use the compiled-in stdlib, using this example:
http://chaiscript.com/examples.html#ChaiScript_Compiled_in_Stdlib_Example
if you are not separately compiling your own stdlib dll/so.

**Comment by kxait** [comment]
That fixed it. Thanks. How would I go about not including the stdlib?

**Comment by lefticus** [comment]
Read this for some more info: http://discourse.chaiscript.com/t/slow-build-times/94/3?u=lefticus
