### ISSUE TITLE
chaiscript::ChaiScript move constructor/assignment

### ISSUE THREAD

**Issue by therocode** [ChaiScript/ChaiScript#252]
* Compiler Used: clang
 * Operating System: Linux
 * Architecture (ARM/x86/32bit/64bit/etc): 64it
 
As far as I can tell, the ChaiScript class does not implement move semantics. Doing:

            chaiscript::ChaiScript script;
            chaiscript::ChaiScript script2 = std::move(script);

Results in a compilation error: use of deleted function ‘chaiscript::ChaiScript::ChaiScript(chaiscript::ChaiScript&&)

Why does it not implement this? It would be useful to have since you can then decouple loading/setup from usage by creating and loading the scripts elsewhere and pass them to where you use them. This can be achieved with unique_ptr but I wonder why it's not possible on the naked objects.

**Comment by therocode** [comment]
Looking in the source, I assume this is due to it containing a couple of mutexes which indeed can't be moved either. However, as far as I know, isn't it valid to set the mutexes up inside std::shared_ptrs and then implement a move constructor which just moves these as usual?

**Comment by lefticus** [comment]
I would be very reluctant to add a layer of indirection to the mutexes. However, if you care about move-ability and *don't* care about thread safety, you could probably build with `-DCHAISCRIPT_NO_THREADS` and then be able to move your ChaiScript object around.

Alternatively, if moveability is important to you, you could wrap your ChaiScript object in it's entirety in a `std::unique_ptr<>`
