### ISSUE TITLE
gcc 5.3.0 warnings

### ISSUE THREAD

**Issue by therocode** [ChaiScript/ChaiScript#254]
* Compiler Used: Gcc 5.3.0
 * Operating System: Arch Linux
 * Architecture (ARM/x86/32bit/64bit/etc): 64bit
 
I am getting compiler warnings when only just including the chaiscript.hpp file. 

Warnings caught with -Werror: http://hastebin.com/rigecehina.cs

As seen it is in the arithmetic operators regarding float<->int stuff. I am thinking this one can be fixed by replacing:

t *= u;

With:

t = static_cast<T>(t * u);

But it might be odd replacing the compound operations with non compound ones, in case T and U have custom overloads of the operators? I am not sure how these functions are used, it is hard for me to tell. If you give a green light for this change, I'll make a pull request.

**Comment by lefticus** [comment]
For that particular block of code the correct thing to do is add it to the list of surgically disabled warnings here:

https://github.com/ChaiScript/ChaiScript/blob/develop/include/chaiscript/dispatchkit/boxed_number.hpp#L44-L56
