### ISSUE TITLE
[Feature Request]Built-in to get a random number

### ISSUE THREAD

**Issue by define-private-public** [ChaiScript/ChaiScript#255]
Seeing as C has the `rand()` function builtin, it might be kind of nice to have it part of ChaiScript's standard library.  Even though it's only one line for the programmer to add this in themselves, this is nice to have built in.

**Comment by lefticus** [comment]
I might be more inclined towards some of the C++11 random number generations facilities instead, http://en.cppreference.com/w/cpp/numeric/random, thoughts?

**Comment by roig** [comment]
I think that it's better to not include those functions and let the user of the library add what really needs.

**Comment by totalgee** [comment]
I'd think this kind of thing should be exposed as an "extra" (https://github.com/ChaiScript/ChaiScript_Extras), rather than a core part of the scripting language.  Then, if you want it, you'd just include the helper header and bootstrap it...just like with the functions of the math library.

**Comment by lefticus** [comment]
Closing in favor of the ChaiScript_Extras option https://github.com/ChaiScript/ChaiScript_Extras/issues/3
