### ISSUE TITLE
[Discussion] Use a Bytecode pattern instead of Syntax Tree for the VM

### ISSUE THREAD

**Issue by define-private-public** [ChaiScript/ChaiScript#266]
Rather than posting an issue, I'd like to have a discussion on the feasibility of switching ChaiScript from a Syntax Tree based evaluation over to a ByteCode pattern.  The main reason behind this would be performance.  What would need to be done for ChaiScript to use this under the hood.

**Comment by lefticus** [comment]
I have moved this conversation over to the discourse site: http://discourse.chaiscript.com/t/moving-to-a-bytecode-representation/186
