### ISSUE TITLE
Change README.md to reflect C++ standard change

### ISSUE THREAD

**Issue by haikarainen** [ChaiScript/ChaiScript#268]
The readme file states that you need C++11 support for chaiscript, but it seems like it needs C++14 these days.

 * Compiler Used: gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
 * Operating System: Fedora 23
 * Architecture (ARM/x86/32bit/64bit/etc): x86_64

**Comment by lefticus** [comment]
If you are using `master` or any of the official releases, C++11 is still the correct compiler to use. `develop` is being heavily re-worked right now to make it C++14, and is in a significant state of flux.

**Comment by haikarainen** [comment]
Hmm @lefticus I just some hour ago did a clone of master, after some inspection that clone seems to compile with c++14, and when I tried to build my library with it I got compilation errors (IIRC it didnt find std::make_unique, which is c++14)

Either I have done something very strange, or something is iffy with your repo.

I basically did

`git clone https://github.com/Chaiscript/Chaiscript`

I typed it manually so it would be very weird if I cloned your production or something.

**Comment by lefticus** [comment]
`develop` is the default branch if you clone, you'd want to `git checkout master` but really your absolute best bet for the most proven and up to date code is to get the last release, which was only published a week or so ago: `git checkout v5.8.3`

**Comment by lefticus** [comment]
It's normally my goal to make develop stable and useful, but I cannot currently guarantee that that's the case because of the reworking I've been doing - sorry!

**Comment by haikarainen** [comment]
I see, well thanks again for a wonderful language & library! :+1:  I'll get the release if anything turns out problematic
