### ISSUE TITLE
samples/example.cpp crashes

### ISSUE THREAD

**Issue by rmpowell77** [ChaiScript/ChaiScript#269]
* Compiler Used:
clang
 * Operating System:
Mac 10.11.4
 * Architecture (ARM/x86/32bit/64bit/etc): 
x86 

### Expected Behavior 
samples/example.cpp should run without crashing
### Actual Behavior 
crashes

I think the fix is:
-  chai.add(var(&system), "system");
+  chai.add_global(var(&system), "system");

**Comment by lefticus** [comment]
Closed with #270
