### ISSUE TITLE
type_info' is not a member of 'std'

### ISSUE THREAD

**Issue by richardlalancette** [ChaiScript/ChaiScript#271]
* Compiler Used: VS2013
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): win32
 

### Expected Behavior 
Building without error

### Actual Behavior 
Compiling error: type_info' is not a member of 'std'

### Minimal Example to Reproduce Behavior

#include chaiscript/chaiscript.hpp

then build.

**Comment by richardlalancette** [comment]
Temporary resolved using this: https://answers.unrealengine.com/questions/229449/stdtype-info-fails-to-build-in-development-configu.html

**Comment by lefticus** [comment]
I need to know:

1) which version of ChaiScript you are compiling
2) have you disabled rtti in your build?

**Comment by richardlalancette** [comment]
chaiscript 5.8.1
And yes, we use a custom RTTI framework.

**Comment by richardlalancette** [comment]
Feel free to close this since it is to do with not having RTTI.

**Comment by lefticus** [comment]
Then it is impossible for you to use ChaiScript. RTTI must be enabled so that ChaiScript internally can determine the types of objects it is working with.

**Comment by richardlalancette** [comment]
Yep, makes sense.
