### ISSUE TITLE
error C3861: '__uncaught_exception': identifier not found

### ISSUE THREAD

**Issue by richardlalancette** [ChaiScript/ChaiScript#272]
* Compiler Used: vs2013
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): win32
 

### Expected Behavior 
builds
### Actual Behavior 
Error	1	error C3861: '__uncaught_exception': identifier not found	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\concrt.h	4774	1

### Minimal Example to Reproduce Behavior
#include chaiscript/chaiscript.hpp
build

Note: Followed a few threads and ended up working around this by doing
#include eh.h just before including #include chaiscript/chaiscript.hpp

**Comment by richardlalancette** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/811347/compiling-vc-12-0-with-has-exceptions-0-and-including-concrt-h-causes-a-compiler-error

**Comment by richardlalancette** [comment]
https://github.com/cginternals/glbinding/issues/157

**Comment by lefticus** [comment]
I need to know:

1) which version of ChaiScript you are compiling
2) have you disabled exceptions in your build?

**Comment by richardlalancette** [comment]
chaiscript 5.8.1
Our engine has exception disabled, yes.

**Comment by lefticus** [comment]
Then it is impossible for you to use ChaiScript. Exceptions must be enabled for it to work correctly.
