### ISSUE TITLE
std::bad_cast::bad_cast already defined?

### ISSUE THREAD

**Issue by richardlalancette** [ChaiScript/ChaiScript#273]
* Compiler Used: vs2013
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): win32
 

### Expected Behavior 
builds correctly

### Actual Behavior 
Error	3	error LNK2005: "public: __thiscall std::bad_cast::bad_cast(class std::bad_cast const &)" (??0bad_cast@std@@QAE@ABV01@@Z) already defined in LovecraftApp.obj	E:\Projects\Github\lovecraft\build\vs2013\LIBCMTD.lib(stdexcpt.obj)	Lovecraft
Error	4	error LNK2005: "public: __thiscall std::bad_cast::bad_cast(char const *)" (??0bad_cast@std@@QAE@PBD@Z) already defined in LovecraftApp.obj	E:\Projects\Github\lovecraft\build\vs2013\LIBCMTD.lib(stdexcpt.obj)	Lovecraft
Error	5	error LNK2005: "public: virtual __thiscall std::bad_cast::~bad_cast(void)" (??1bad_cast@std@@UAE@XZ) already defined in LovecraftApp.obj	E:\Projects\Github\lovecraft\build\vs2013\LIBCMTD.lib(stdexcpt.obj)	Lovecraft

### Minimal Example to Reproduce Behavior
#include chaiscript/chaiscript.hpp

**Comment by lefticus** [comment]
So, I regularly build on Windows 10 with MSVC 2013 - something very very strange is going on with all of the error reports you are making - something I've never seen or heard of before. I need MUCH more detail.

Compiler flags, version of chaiscript, specific example code anything you can give me.

This most recent one for sure has absolutely nothing to do with ChaiScript, and must be related to how you are building and linking your application.

**Comment by richardlalancette** [comment]
This is most likelly have to do with our engine not having RTTI and Exceptions.

Let's just close the last 3 issues I have opened since it is very unlikely that I can enable them back.
