### ISSUE TITLE
[Feature Request] Way to get the execution context of a chaiscript call from inside the call itself

### ISSUE THREAD

**Issue by Sixmorphugus** [ChaiScript/ChaiScript#277]
For example, my C++ logging system uses this "info" macro.
#define info(string) diagnosticLog(p::INFO, __FILE__, __FUNCTION__, __LINE__, string);
Which uses compiler-defined values to work out where the print statement happened during compilation to produce:
"INFO[fake/path/file.cpp (fakeFunction:12)]: string"

Can chaiscript have something that I can use like I used __FILE__, __FUNCTION__ and __LINE__ in MSC?

**Comment by roig** [comment]
Hello, don't know if this is what you are looking exactly, but to check for errors when you call a script function from c++, you can use this:

from c++:
> 		try {
			// Call your script function
		} catch (chaiscript::exception::eval_error &e) {
                        // if something happens, you can get a pretty print of the error that will say you the line
                        // number inside your script that is failing calling the pretty_print() function from the
                        // exception.

                       // For example in my system make this:
			log::logMsg(e.pretty_print(), log::Level::LEVEL_ERROR);
		}

What this function will print is something like that:

> Error: "Two expressions missing line separator" in 'PlayerPrototype1.chai'  at (75, 18)

As you can see you can get the line and colum of the error in your script.

Maybe what we can add to this exception are methods for retrieving the file, line and column, but that's something that looking into the source file of that exception you can extend.

Hope it helps.

**Comment by lefticus** [comment]
What I really need to do is just add stuff for getting the context. The hard part is that a child parse node doesn't know anything about its parent, so it will require some kind of special support to get it working, but I think it's doable.
