### ISSUE TITLE
5.8 breaks registering lambda functions to a module

### ISSUE THREAD

**Issue by haikarainen** [ChaiScript/ChaiScript#280]
* Compiler Used: gcc (GCC) 6.1.1 20160707
 * Operating System: Arch Linux
 * Architecture (ARM/x86/32bit/64bit/etc):  x86_64
 
Please see this issue: https://github.com/haikarainen/kit/issues/12

The errounous line: https://github.com/haikarainen/kit/blob/master/src/Kit/ScriptLib.cpp#L467

```c++
{chaiscript::fun<void(kit::Application&,bool)>([](kit::Application& a, bool b) { a.getWindow()->setVSync(b); }), "setVSync"}
```

Compiles fine on 5.7.0, breaks on 5.8.x

**Comment by haikarainen** [comment]
The unit test from #139  seems to be missing (https://github.com/ChaiScript/ChaiScript/blob/master/unittests/cpp_lambda_test.cpp)

Are lambda functions no longer supported? :/

**Comment by lefticus** [comment]
The appropriate test is here now: https://github.com/ChaiScript/ChaiScript/blob/master/unittests/compiled_tests.cpp#L33-L48

In the referenced #139 I claimed that automatic type deduction of lambdas was "impossible." I since learned (at C++Now 2015) that it is not impossible, and implemented auto type deduction.

**Comment by haikarainen** [comment]
Sorry if I'm being a pain, but aren't I specifying the return type by providing the signature in the template type? (`<void(kit::Application&,bool)>`)

Also, I'm having a hard time understanding the syntax for the lambda in one of the examples you provided, what does the `->std::string` part do in the following line?

```
  chai.add(chaiscript::fun([]()->std::string { return "hello"; } ), "f1");
```

Thanks for the quick response!

**Comment by haikarainen** [comment]
Disregard that first part, I think I understand now!

**Comment by lefticus** [comment]
Certainly, I will clarify just to make sure everyone is clear.

```
[]()->std::string { return "hello"; } // explicit return type of std::string
```

```
[]() { return "hello"; } // implicit return type of const char *
```

```
[]() { return std::string("hello"); } // implicit return type of std::string
```

So you may or may not need to specify the return type based on the body of the lambda. Personally, I rarely specify the trailing return type with `->`

On a side note, this is the same syntax available with trailing return types in C++11 and auto return type deduction in C++14.

```
// valid in C++11
auto my_func() -> std::string
{
  return "Hello World";
}
```

```
// valid in C++14
auto my_func()
{
  return std::string("Hello World");
}
```

**Comment by haikarainen** [comment]
I see, I appreciate it, thanks! You may close this if you want
