### ISSUE TITLE
Bad cast with vector of pointers

### ISSUE THREAD

**Issue by lucas-sarie** [ChaiScript/ChaiScript#281]
* Compiler Used: MSVC13
 * Operating System: W7
 * Architecture (ARM/x86/32bit/64bit/etc):  x64
 
I try to exchange vector of custom class pointer between C++ and chaiscript but it seems that there is a bug, here is a small code snippet :

```
class test
{
public:
	test()
	{
		name_ = "test";
	}

	const std::string& GetName()
	{
		return name_;
	}

private:
	std::string name_;
};

std::vector<test*> GetTestVector()
{
	std::vector<test*> v;
	v.push_back(new test());
	return v;
}

int main(int ac, char** av)
{
	chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());

	chai.add(chaiscript::bootstrap::standard_library::vector_type<std::vector<test*>>("VectorTest"));
	chai.add(chaiscript::fun(GetTestVector), "GetTestVector");
	chaiscript::utility::add_class<test>(chai, "test",
	{ // No constructor },
	{ { chaiscript::fun(&test::GetName), "GetName" } }
	);

	try
	{
		chai.eval(R"(
			var testVec = GetTestVector()
			var myTest := testVec[0]
			print(myTest.GetName())
		)");
	}
	catch (std::exception e)
	{
		std::cout << "ERROR : " << e.what() << std::endl;
	}
```

it crashes in the GetName method, the problem is that 'this' is cast from test** to test* (so GetName is called with this pointer as test** instead of test*) then it segfault. Indeed in the boxed_value test returned from the vector access is store as a test** and not as a test* maybe this is the problem.

I don't know where exactly is the mistake but it is easy to reproduce and I hope to fix ;)

Thanks

**Comment by lefticus** [comment]
Fixed in v5.8.3 already.
