### ISSUE TITLE
passing references via parameters fails if there's a long parameter

### ISSUE THREAD

**Issue by SytheMarket** [ChaiScript/ChaiScript#283]
* Compiler Used: visual studio 2015 c++ compiler
 * Operating System: win10
 * Architecture (ARM/x86/32bit/64bit/etc): amd 64
 
I checked the memory location of ox, oy (printf("%x, %x\n", &ox, &oy);) inside the FindBitmap function. When transparentColor is a long the location is offset by some bytes: "ox: 7a044cc, oy: 7a0470c" (with transparentColor as long), "ox: 7a04664, oy: 7a04514" (with transparentColor as short).

Not sure internally how the parameters are passed but it seems likely the long type is being assigned the wrong size for the architecture when calculating memory offsets.

So to be clear, when transparentColor is an int, below, the references are correctly passed and able to be set. When transparentColor is a long, setting fails and the variables retain their original value. Possibly the write operation still occurs over other memory.

### Expected Behavior 
"found at 1, 2"
### Actual Behavior 
"found at 0, 0"
### Minimal Example to Reproduce Behavior
bool FindBitmap(int &ox, int &oy, int bmpID, int x1, int y1, int x2, int y2, int colorTolerance, int deformationTolerance, long transparentColor, bool mask) {
ox = 1; oy =2; return true;
}
chai.add(chaiscript::fun(static_cast\<bool(*)(int &, int &, int, int, int, int, int, int, int, long, bool)\>(&FindBitmap)), "FindBitmap");

chai.eval( "var x = 0; var y = 0; if ( FindBitmap ( x, y, 0, 0,0,800,800, 0, 0, 0, false ) ) {	print("found at " + to_string(x) + ", " + to_string(y))}" );

**Comment by lefticus** [comment]
Reproduced on gcc also:

```
#include <chaiscript/chaiscript.hpp>
#include <chaiscript/chaiscript_stdlib.hpp>




bool FindBitmap(int &ox, int &oy, long transparentColor) {
  ox = 1; 
  oy = 2; 
  return true;
}

int main()
{
  chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());

  chai.add(chaiscript::fun(&FindBitmap), "FindBitmap");
  chai.eval( "var x = 0; var y = 0; if ( FindBitmap ( x, y, 0) ) { print(\"found at \" + to_string(x) + \", \" + to_string(y))}" );

}
```

Note that if you pass it the correctly sized value and don't rely on automatic conversion from int to long for the long parameter:

#include <chaiscript/chaiscript.hpp>
#include <chaiscript/chaiscript_stdlib.hpp>




bool FindBitmap(int &ox, int &oy, long transparentColor) {
  ox = 1; 
  oy = 2; 
  return true;
}

int main()
{
  chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());

  chai.add(chaiscript::fun(&FindBitmap), "FindBitmap");
  // Note the 'l' after the 0 in the FindBitmap call
  chai.eval( "var x = 0; var y = 0; if ( FindBitmap ( x, y, 0l) ) { print(\"found at \" + to_string(x) + \", \" + to_string(y))}" );
}
```

The error does not reproduce. This may give you a work-around until I figure out what's going on.

-Jason

**Comment by SytheMarket** [comment]
Thanks for that Jason.

I'm now using ints for everything. In reality we only need three bytes to express "true colour". Unsigned long is the convention because it gives you an alpha channel (i.e. 32bit colour) but we don't use the alpha channel at all so even a regular (signed) int works fine for us. All the same thought I should let you know since it did appear to be writing over some (other) memory.

Chaiscript is really good btw. Thanks for working on it!

**Comment by lefticus** [comment]
I did find and fix this issue and committed it to a new tag for v5.8.4 https://github.com/ChaiScript/ChaiScript/releases/tag/v5.8.4 hopefully this works for you.

**Comment by lefticus** [comment]
Fixed here: https://github.com/ChaiScript/ChaiScript/commit/4b81a24a0a37da68bf1f55240e676e6ba5887a1f
