### ISSUE TITLE
Incorrect prefix negation operator precedence

### ISSUE THREAD

**Issue by stephenberry** [ChaiScript/ChaiScript#285]
* Compiler Used: MSVC 2015
 * Operating System: Windows 10
 * Architecture: x64
 
### Minimal Example to Reproduce Behavior
``` C++
struct Squared {};
template <typename T>
inline T operator*(const T& lhs, const Squared& rhs)
{
   return lhs*lhs;
}
```

### Expected Behavior (standard C++)
```
std::cout << -2 * Squared() << '\n';
```
Outputs: ```4```

### Actual Behavior (ChaiScript)
```
chaiscript_instance->add(chaiscript::constructor<Squared()>(), "Squared");
chaiscript_instance->add(chaiscript::fun([](const int lhs, const Squared& rhs) { return lhs*rhs; }), "*");
```
Script:
```
print(-2*Squared())
```
Outputs: ```-4```

- The same error is reproducible with double and float

**Comment by lefticus** [comment]
@jonathandturner thought you'd like to see this one.
