### ISSUE TITLE
Destruction Assertion Failure (vector out of range)

### ISSUE THREAD

**Issue by stephenberry** [ChaiScript/ChaiScript#286]
* Compiler Used: MSVC 2015
 * Operating System: Windows 10
 * Architecture: x64
 

### Minimal Example to Reproduce Behavior
All the code necessary to generate a ```vector subscript out of range``` Debug assertion is below:
``` C++
#include "chaiscript/chaiscript.hpp"
#include <chaiscript/chaiscript_stdlib.hpp>

using namespace chaiscript;

struct TNT
{
   std::unique_ptr<ChaiScript> chai = std::make_unique<ChaiScript>(Std_Lib::library());
};

int main()
{
   std::shared_ptr<ChaiScript> chai = std::make_shared<ChaiScript>(Std_Lib::library());

   chai->add(constructor<TNT()>(), "TNT");

   std::shared_ptr<double> match = std::make_shared<double>();
   chai->add(fun([=]() {  chai->add(var(match), "match"); }), "ignite");

   chai->eval("var tnt = TNT()");

   return 0;
}
```

* Note that the ```std::shared_ptr<double> match ``` being copied to the lambda, which is added to the initial ChaiScript instance is necessary to produce the error. Creating an instance of TNT by itself will not cause an error.

**Comment by lefticus** [comment]
I don't think it's possible to fix this. You've created a situation with the ChaiScript object owns itself.

It's a cyclical `shared_ptr` ownership, which is basically guaranteed to create a memory leak / do weird things at application end time.

**Comment by stephenberry** [comment]
I see, it's because I'm passing my chai object by value into a function registered to it.

Here's an easy fix: ```chai->add(fun([=, &chai]() {  chai->add(var(match), "match"); }), "ignite");```

This should be fine if I pass ```chai``` by reference, right?

**Comment by lefticus** [comment]
Your `chai` object is a `shared_ptr`, what you'd probably want to do is capture the raw pointer, using a C++14 style capture. I think you have that in MSVC.

```
chai->add(fun([=, chai = chai.get()]() { chai->add(var(match), "match"); }), "ignite");
```

Otherwise:


```
auto chai_ptr = chai.get();
chai->add(fun([=, chaiptr]() { chaiptr->add(var(match), "match"); }), "ignite");
```

**Comment by stephenberry** [comment]
Excellent, thanks! You can close this issue.
