### ISSUE TITLE
detail::Return_Value is thrown instead of returned

### ISSUE THREAD

**Issue by chronos38** [ChaiScript/ChaiScript#289]
* Compiler Used: MSVC 12 (Visual Studio 2013)
 * Operating System: windows 10 anniversary update
 * Architecture (ARM/x86/32bit/64bit/etc): Win32
 

### Expected Behavior 
Return value of chaiscript lambda should return value internally.
### Actual Behavior 
Return value of chaiscript lambda gets thrown then catched and then returned.
### Minimal Example to Reproduce Behavior
```
#include <chaiscript/chaiscript.hpp>
#include <chaiscript/chaiscript_stdlib.hpp>
#include <iostream>

using std::cout;
using std::cerr;
using std::endl;

int main()
{
    chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());

    chai.add(chaiscript::fun([](std::function<chaiscript::Boxed_Value(int)> f) {
                 cout << chaiscript::boxed_cast<int>(f(42)) << endl;
             }),
             "f");
    chai.eval("f(fun (int i) { return i; })");

    return 0;
}
```

**Comment by chronos38** [comment]
It's in file chaiscript_eval.hpp, this particular code:
```
template<typename T>
    struct Return_AST_Node final : AST_Node_Impl<T> {
        Return_AST_Node(std::string t_ast_node_text, Parse_Location t_loc, std::vector<AST_Node_Impl_Ptr<T>> t_children) :
          AST_Node_Impl<T>(std::move(t_ast_node_text), AST_Node_Type::Return, std::move(t_loc), std::move(t_children)) { }

        Boxed_Value eval_internal(const chaiscript::detail::Dispatch_State &t_ss) const override{
          if (!this->children.empty()) {
            throw detail::Return_Value(this->children[0]->eval(t_ss));
          }
          else {
            throw detail::Return_Value(void_var());
          }
        }
    };
```

Is there a reason this is done?

**Comment by lefticus** [comment]
It's a poor design decision that I've yet to fix. This is not a bug, the value is handled internally correctly and returned to the caller, right?

**Comment by lefticus** [comment]
Actually, I do try to eliminate as many "return exceptions" as possible, but there seems to be a hole in that code when it comes to lambdas.

**Comment by lefticus** [comment]
The key to understand here is that:

```
def f()
{
  return 1;
}
```

and

```
def f()
{
  1;
}
```

Are equivalent code. ChaiScript has for a while now simply eliminated the return statement where possible. This return elimination was not implemented for lambdas - it is now.
