### ISSUE TITLE
Unable to compile with Visual Studio 2015

### ISSUE THREAD

**Issue by rachelnertia** [ChaiScript/ChaiScript#291]
Hi. This is my first time trying to use ChaiScript, so there's probably some simple step I am missing, but I am completely unable to get off the ground. Simply including chaiscript.hpp is enough to cause these errors. My main function is completely empty in. I'm using the latest version of the headers, with vc14, on Windows 10. Neither a 32 or 64-bit configuration works. Help!

Here's the code:

```
#include <chaiscript/chaiscript.hpp>
int main() {}
```

Here's the compiler output:

```
1>d:\documents\dev\chaiscript\include\chaiscript\dispatchkit\type_info.hpp(52): error C2134: 'chaiscript::Type_Info::operator ==': call does not result in a constant expression
1>  d:\documents\dev\chaiscript\include\chaiscript\dispatchkit\type_info.hpp(52): note: failure was caused by call of undefined function or one not declared 'constexpr'
1>  d:\documents\dev\chaiscript\include\chaiscript\dispatchkit\type_info.hpp(60): note: see declaration of 'chaiscript::Type_Info::operator =='
1>d:\documents\dev\chaiscript\include\chaiscript\dispatchkit\type_info.hpp(57): error C2134: 'chaiscript::Type_Info::operator ==': call does not result in a constant expression
1>  d:\documents\dev\chaiscript\include\chaiscript\dispatchkit\type_info.hpp(57): note: failure was caused by call of undefined function or one not declared 'constexpr'
1>  d:\documents\dev\chaiscript\include\chaiscript\dispatchkit\type_info.hpp(66): note: see declaration of 'chaiscript::Type_Info::operator =='
```

This output seems like nonsense to me as the == operator is literally defined as constexpr.

Any help would be very much appreciated as I'd love to give working with ChaiScript a whirl. Thanks.

**Comment by lefticus** [comment]
Sounds like you have not updated your MSVC to the latest update (update 3). https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs 

Also, for the best stability, I suggest you go with the latest release instead of `develop` (currently 5.8.5 https://github.com/ChaiScript/ChaiScript/releases/tag/v5.8.5)

**Comment by rachelnertia** [comment]
It took all night to install the update but yeah, that was the problem *shakes fist at Microsoft*. Thanks for the help!
