### ISSUE TITLE
Lambda Function Syntax [Improvement?]

### ISSUE THREAD

**Issue by stephenberry** [ChaiScript/ChaiScript#292]
Is there a design or semantics reason why the `fun` specifier is required on lambda functions?  
For example: `square = fun[](x) { return x * x }`

It seems like `fun` is frivolous and the same meaning can be inferred from: `square = [](x) { return x * x }`

I'm guessing that this isn't allowed because it would be difficult to parse the difference between an array and a lambda function with captures.

**Comment by lefticus** [comment]
We implemented the `fun` version before C++11 was released (2009). We went to add a version that didn't require the `fun` but we didn't have capture support yet... So it's been an evolution.

At this point I think we'd have a pretty serious parsing problem trying to add just the `[](){}` version.

However, you can eliminate the `[]` in chaiscript, `fun(x){ return x*x; }` is perfectly valid.

**Comment by stephenberry** [comment]
Thanks for the reply. Feel free to close this issue as I was just wondering the reasoning behind the requirement. You've done an excellent job integrating ChaiScript with C++11 syntax and functionality.
