### ISSUE TITLE
to_json

### ISSUE THREAD

**Issue by toutant** [ChaiScript/ChaiScript#293]
- Compiler Used:
- Operating System:
- Architecture (ARM/x86/32bit/64bit/etc): 
### Expected Behavior

be able to turn vector list to json string
### Actual Behavior

produces - throw std::runtime_error("Unknown object type to convert to JSON");
### Minimal Example to Reproduce Behavior

```
typedef std::vector<std::pair<std::string, std::string>> data_list;
data_list my_list;
// add items in here
chai.add(chaiscript::bootstrap::standard_library::vector_type<data_list>("DataList"));
chai.add(chaiscript::bootstrap::standard_library::pair_type<data_list::value_type>("DataElement"));
chai.add(chaiscript::var(&my_list), "data_list");

// to_json in script produces - throw std::runtime_error("Unknown object type to convert to JSON");
```

std::string should be basic type ?

**Comment by lefticus** [comment]
The problem isn't the string, it's everything else.

ChaiScript has no way of knowing how to convert a `vector<pair<>>` and if it did, it doesn't know how to convert a `pair<>` as there's no direct mapping from that to a type in JavaScript.
