### ISSUE TITLE
Simplify syntax for class member references [Improvement]

### ISSUE THREAD

**Issue by stephenberry** [ChaiScript/ChaiScript#302]
Obviously we can't have a pointer to a member reference, so I expose class member references to ChaiScript as functions. What I would like is the ability to remove the requirement of parenthesis for class member references.

Example: C++
``` C++
struct MyClass
{
MyClass(double& x) : x(x) {}

double& x;
};
```
Registration:
``` C++
chai.add(chaiscript::fun([](MyClass& my_class) { return my_class.x; }), "x");
```
ChaiScript:
```
my_class_instance.x() = 5.0;
```

Desired ChaiScript Syntax:
```
my_class_instance.x = 5.0;
```

Like in C++, I would like to be able to access and assign to references without the function call syntax. This may seem minor, but it is actually significant to enabling me to write generic code for handling class members.

I'm not sure how best to approach this. Is there currently a way of handling member references that I'm unaware of?

**Comment by lefticus** [comment]
I've don't think I've tried this nor had any test for it, but what does:

```
chai.add(chaiscript::fun(MyClass::x) , "x");
```

Do, like a non-reference member?

**Comment by stephenberry** [comment]
Trying this gives me a compile error: `illegal reference to non-static member`

**Comment by lefticus** [comment]
Ok, that's ultimately what needs to be fixed then. Have you guys moved to the `develop` branch?

**Comment by stephenberry** [comment]
Yes, all development and testing is off ChaiScript's `develop` branch.
