### ISSUE TITLE
Optional Parameters.

### ISSUE THREAD

**Issue by Brandantl** [ChaiScript/ChaiScript#309]
* Compiler Used: MSVC 14.0
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): 32 bit.

ChaiScript appears to not like functions with optional parameters. For example, this function (DoSomething) will cause a dispatch error, and you have to do some annoying stuff to work around it in ChaiScript like "\0".c_str();.

```
inline char DoSomething(char c = 0)
{
    return c;
}
```

In theory, you should be able to call DoSomething like DoSomething() and DoSomething('A');

**Comment by lefticus** [comment]
This is not an issue with ChaiScript, it is an issue with C++. That is, it is not possible for ChaiScript to know that you have provided a default value for a parameter, C++ has no mechanism for this.

What you need to do is register the function both ways:

```cpp
chai.add(chaiscript::fun(&DoSomething), "DoSomething");
chai.add(chaiscript::fun([](){ return DoSomething(); }), "DoSomething");
```

Note in the second case I'm using a lambda function to wrap the call to DoSomething with 0 parameters. This is the cleanest way to accomplish what you want.
