### ISSUE TITLE
how to compile and run in header-only way ?

### ISSUE THREAD

**Issue by pubcoder** [ChaiScript/ChaiScript#313]
* Compiler Used: g++ 6.2.1-5
 * Operating System: Debian GNU Linux
 * Architecture (ARM/x86/32bit/64bit/etc): 64bit
 
The project introduction page says that ChaiScript "uses header-only approach" and hence I am trying the example "main.cpp" from the intro page like this:

`g++ -std=c++14 -I../ChaiScript-5.8.5/include/ main.cpp`

and compiler complains that it cannot find implementations for dlsym and dlerror.
So I try this instead:

`g++ -std=c++14 -I../ChaiScript-5.8.5/include/ main.cpp -ldl`

When I try to run the `./a.out` it complains that it cannot find `./libchaiscript_stdlib-5.8.5.dll`, `./libchaiscript_stdlib-5.8.5.so` etc.

So this does not look like "header-only" library, in fact it depends on dynamic libraries, or perhaps I am missing something how to compile it properly?
Frankly, I did not compile anything except this small program. Any help is appreciated.

### Expected Behavior 

compile and run as described.

### Actual Behavior 

asks for dynamic linking library, then asks for dynamically linked library.

### Minimal Example to Reproduce Behavior

```
/// main.cpp

#include <chaiscript/chaiscript.hpp>

double function(int i, double j)
{
  return i * j;
}

int main()
{
  chaiscript::ChaiScript chai;
  chai.add(chaiscript::fun(&function), "function");

  double d = chai.eval<double>("function(3, 4.75);");
}

```

**Comment by pubcoder** [comment]
argh! I should have tried the second example with `Std_Lib::library()` constructor, sorry for the noise

**Comment by lefticus** [comment]
Because of this confusion and related issues ChaiScript 6 (currently on develop branch) has the stdlib compiled in by default, and you have to go through some effort to make it a separate compile.
