### ISSUE TITLE
Context value __LINE__ not working.

### ISSUE THREAD

**Issue by aggsol** [ChaiScript/ChaiScript#314]
* Compiler Used:
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Ubuntu 16.04

### Expected Behavior 
Output: current line: 1

### Actual Behavior 
```
terminate called after throwing an instance of 'chaiscript::exception::eval_error'
  what():  Error: "Can not find object: __LINE__" 
```

### Minimal Example to Reproduce Behavior

```
    chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());
    chai.eval("print(\"current line: \" + __LINE__);"); 
```

**Comment by lefticus** [comment]
That is not yet in any official release, it's in the current develop branch. What version are you building?

**Comment by aggsol** [comment]
5.8.6

**Comment by lefticus** [comment]
Then you'll need to move to the develop branch if you need that feature.
