### ISSUE TITLE
Crash on exit in ~Thread_Storage() (Windows, VS2015)

### ISSUE THREAD

**Issue by totalgee** [ChaiScript/ChaiScript#318]
* Compiler Used: **Visual Studio C++ 2015**
 * Operating System: **Windows 10 Pro (Version 1607)**
 * Architecture (ARM/x86/32bit/64bit/etc): **Intel x64 (i7)**
 

### Expected Behavior 

Hi there, I've seen some issues (such as #225) that relate to thread_local storage, but I think my issue is different from that one.  I've compiled my program on Windows, using VS2015 (not MinGW as in #225), with threading enabled (the default).  On program exit, I get a crash as an instance of the class Thread_Storage is destroyed.  There, it's calling t().erase(m_key), but the thread_local map is empty, so the call to erase throws.

I don't know if this is simply a matter of adding a check for whether the key exists first, or if it's a symptom of some other underlying cause...?  (Incidentally, if I add such a check, the crash goes away; I'll probably submit a PR for that, if you think it's a fine fix then we're done!)

Any ideas on anything else I should check?  (If I do turn off threading support by defining CHAISCRIPT_NO_THREADS the crash does indeed go away...)  At the moment, I'm not doing any explicit multi-threading; all my Chai scripting and program execution is in the same thread, and my thread id is the same when the Thread_Storage() constructor is called at startup as when its destructor is called at exit.  But the map is empty at that point...likely because they key is not added to the map in the constructor, and since the Thread_Storage is never accessed using dereferencing (operator->() or operator*()), that means it's never added to the map...  So I think my fix should be fine.

Thanks,
Glen.

### Actual Behavior 

Crash on exit on Windows (VS2015), in `~Thread_Storage()`.  No crash on exit for the same program on OS X (with threading enabled).

### Minimal Example to Reproduce Behavior

I think, in my particular case, my (three) Thread_Storage instances are created when I add some ChaiScript type_conversions.  I have these lines in my program's ChaiScript bootstrapping code:

```c++
chai = std::make_unique<ChaiScript>();

chai->add(type_conversion<double, float>());
chai->add(type_conversion<int, float>());
chai->add(type_conversion<std::string const&, char const*>([](std::string const& s) { return s.c_str(); }));
```

**Comment by totalgee** [comment]
Of course, calling unordered_map::erase() with a key that's not found, or for an empty map, should not throw or crash.  So I suspect the real problem is something else, and my "fix" would just be hiding some other problem...?

**Comment by totalgee** [comment]
I can reproduce the problem with a simplified program (one that just copies ChaiScript's Thread_Storage class into a file).  When an object of that type is destroyed outside the main() function (e.g. a global variable containing a unique_ptr), the assertion fails:

    Expression: vector subscript out of range

This is when trying to find the item in the unordered_map's hash bucket...the vector in question is not in a valid state (or has been freed).  Note that this has nothing to do with thread_local -- I can reproduce this in a program where the member is not declared thread_local, so I think it's to do with how (static?) objects are destroyed on Windows...or something?

**Comment by lefticus** [comment]
Any chance that your `chai` object is a global?

**Comment by totalgee** [comment]
Yes, my `chai` object is a global (std::unique_ptr).

Here's a standalone program that shows the problem, crashes on exit on Windows 10, compiled with VS2015.

```c++
#include <unordered_map>
#include <memory>

// (Class copied from chaiscript_threading.hpp)
template<typename T>
class Thread_Storage
{
public:

    explicit Thread_Storage(void *t_key)
        : m_key(t_key)
    {
    }

    ~Thread_Storage()
    {
        // Checking if it's empty prevents the crash on exit,
        // but doesn't really address the cause of the problem,
        // which seems to be the static data being destroyed
        // before the unique_ptr that holds a Thread_Storage.
//        if (!t().empty()) {
            t().erase(m_key);
//        }
    }

    inline const T *operator->() const
    {
        return &(t()[m_key]);
    }

    inline const T &operator*() const
    {
        return t()[m_key];
    }

    inline T *operator->()
    {
        return &(t()[m_key]);
    }

    inline T &operator*()
    {
        return t()[m_key];
    }


    void *m_key;

private:
    static std::unordered_map<void*, T> &t()
    {
        // The problem happens even when not declared thread_local!
        /*thread_local*/ static std::unordered_map<void *, T> my_t;
        return my_t;
    }
};

using namespace std;
unique_ptr<Thread_Storage<int>> globalScopeThreadCache;

int main()
{
    unique_ptr<Thread_Storage<int>> mainScopeThreadCache;
    int* x = nullptr; // just a dummy we can use as key, it's never dereferenced

    {
        // This doesn't crash
        Thread_Storage<int> t(x);
    }
    // This doesn't crash, either, as the member is destroyed at the end of main()
    mainScopeThreadCache = make_unique<Thread_Storage<int>>(++x);
    *(*mainScopeThreadCache) = 123;

    // This one does crash, when the program exits (on Windows 10, VS2015)
    globalScopeThreadCache = make_unique<Thread_Storage<int>>(++x);
    // Set the map data, to show it doesn't work even when
    // the map contains something...it appears to have been
    // cleared before the destructor is called.
    *(*globalScopeThreadCache) = 456;

    return 0;
}
```

**Comment by lefticus** [comment]
If you make a global ChaiScript then you have the problem that the Thread_Storage object is destructed before the final ChaiScript object is destructed.

In C++ there's no way to guarantee the ordering of these global things, in general, and this is why globals are strongly discouraged in the language.

At the moment I'm not aware of any workaround that will simultaneously allow us to have `thread_local` storage and play nicely with using ChaiScript as a global.

If you have any ideas, let me know.

**Comment by lefticus** [comment]
A workaround for you would be to explicitly destruct your global ChaiScript *before* your `main` exits.

**Comment by totalgee** [comment]
Okay, thanks for the quick answer.  No problem, I'll just add a scripting cleanup call to free my unique_ptr.

**Comment by totalgee** [comment]
For the record, my standalone test program above **also** crashes on OS X...however my program using ChaiScript doesn't!  Maybe down to differences with Cinder (the application framework I'm using) on the two platforms...?  Or just to do with the order of destruction of statics/globals in different object files, or...  Well, who knows, it doesn't matter.
