### ISSUE TITLE
Binding more than 2 arguments

### ISSUE THREAD

**Issue by StanEpp** [ChaiScript/ChaiScript#320]
Currently ChaiScript can't bind more than 2 arguments with the `chaiscript::fun` function, i.e.

> void foo(int x, int y, int z, int u){ ... }
> chai.add(chaiscript::fun(&foo, 3, 4)); // <- is possible
> chai.add(chaiscript::fun(&foo, 3, 4, 5)) // <- not possible

**Comment by Ybalrid** [comment]
Looking at the example and documentation, you should be able to do any sort of thing by passing a lambda to chaiscript::fun. 

as in 
```C++
void foo(int x, int y, int z, int u){ ... }

chai.add(chaiscript::fun([](int x, int z){foo(x,y,3,4);}, "foo");
chai.add(chaiscript::fun([](int x, ){foo(x,3,4,5);}, "foo");
```

You should be able to add much function as you need that way, in any overload possible, and just put "by default" arguments in the body of the lambdas. 

(I may have misunderstood what you're trying to do.  In any case, you need to give the name to call the function you're binding to chai.add)

**Comment by lefticus** [comment]
Yes, the complexity of automatic binding and argument type deduction is really quite complex. By far the easiest way to do it is to wrap it in your own lambda and the best for both you and the library's sake.

I almost completely removed the automatic binding capability because of the complexity of it, but I did figure out how to make it a bit less complex, so I left it in. Plus the single parameter version is really quite handy.

-Jason

**Comment by StanEpp** [comment]
I am aware of the fact that you can achieve this with lambdas. I was only wondering why it is allowed to bind up to two variables? I can understand that binding one variable is convenient for registering member functions, but why binding two variables though? 

Personally I would only allow binding one variable for the mentioned reason above and binding more than two variables should be done with lambdas. That way there would be a more or less clean distinction when to use chaiscripts binding capabilities and when to use a lambda. 

I know this is more of a design discussion. It's just a question which popped up in my mind when I was using automatic binding. I didn't know whether someone forgot to implement binding more than two arguments or there was a particular reason behind it.

**Comment by aggsol** [comment]
I agree with @StanEpp. I would consider removing automatic binding at all a good step to make ChaiScript more bare and explicit. But that is more a matter of taste I assume.
