### ISSUE TITLE
Negative number parsing incorrect when calling as a method

### ISSUE THREAD

**Issue by totalgee** [ChaiScript/ChaiScript#322]
* Compiler Used: Xcode 8.2.1
 * Operating System: OS X 10.11.6
 * Architecture (ARM/x86/32bit/64bit/etc): 64bit (1,8 GHz Intel Core i5)

I would expect the binding of the prefix minus to be stronger than the function calling syntax.

### Expected Behavior 
I'd expect the prefix minus sign (on a number) to bind tighter than the method dot calling syntax.
`-5.numFunc == (-5).numFunc;` (currently false)

### Actual Behavior 
The opposite is true:
`-5.numFunc == -(5.numFunc);` (currently true)

### Minimal Example to Reproduce Behavior

```
def numFunc(x) {
    return x + 10;
}
print("-(5.numFunc) is ${-(5.numFunc)}"); // --> -15
print("(-5).numFunc is ${(-5).numFunc}"); // --> 5

// The following returns the same as -(5.numFunc), but I would expect (-5).numFunc
print("-5.numFunc is ${-5.numFunc}"); // --> -15 (I would have expected 5)
```

**Comment by lefticus** [comment]
Can you verify which version of ChaiScript you are using? I thought I fixed this on the current develop branch.

Thanks!
Jason

**Comment by totalgee** [comment]
I'm running b7e8897, from Dec. 29.

**Comment by lefticus** [comment]
That's interesting... and annoying. I'll check into it when I can.

**Comment by lefticus** [comment]
Closed in 83b7973cb885af928e36195a7cbc6ab8f04a93b6

**Comment by lefticus** [comment]
OK, so I've done more homework on this, and even though it appears that the result is wrong, it's actually following all of the rules of C++ operator precedence.

That is, the unary `-` is not actually part of the number that is parsed.

Consider:

`-value.doSomething()`

This would call doSomething(), then negate the result. Now, C++ does not allow

`-1.doSomething()`

But the rules would apply exactly the same as it was in ChaiScript, because in C++ `.` takes precedence over `-`  http://en.cppreference.com/w/cpp/language/operator_precedence

I'm inclined to change it back to what it was, and require `(-1).doSomething()` if you really want that behavior.

Thoughts?

**Comment by aggsol** [comment]
:+1:  for following the C++ precedence for consistency. This enforces the tight relationship between ChaiScript and C++.

**Comment by totalgee** [comment]
That's fine with me, as long as there's a reason!

I was surprised by this, but I guess it does make sense, when you look at it in terms of C++ operator precedence.  Of course C++ doesn't allow function calls on numbers, and it's debatable this would be the desired behaviour if it were.

Some languages that allow methods on numbers would interpret `-1.something` as `(-1).something`.  As an example, SuperCollider's language does that -- but at the same time, it does not allow `-(1.method)`.  If you wanted that, you'd explicitly have to write `-1 * (1.method)`, or `1.method.neg`.

I discovered that JavaScript, however, actually behaves more or less like ChaiScript.

```javascript
> Number.prototype.addOne = function() { return this + 1; }
[Function]
> -5.3.addOne()
-6.3
> (-5.3).addOne()
-4.3
```

It's actually even more restrictive, because it won't accept a positive integer `5.addOne()` for some reason; you'd have to write `(5).addOne()` or `5..addOne()` (yes, with two dots)...

So I'm fine documenting this and leaving it as it is.  Thanks for digging into it!

**Comment by lefticus** [comment]
Ok, sounds great, thanks for the feedback everyone

**Comment by lefticus** [comment]
Ok, I undid the change, updated the tests, added more tests and put some docs as to why we expect the tests to give specific results.

Closing now.
