### ISSUE TITLE
warning C4602: #pragma pop_macro

### ISSUE THREAD

**Issue by IonutCava** [ChaiScript/ChaiScript#323]
* Compiler Used: MSVC 14.1
 * Operating System: Windows 7
 * Architecture (ARM/x86/32bit/64bit/etc): x64
 
Due to certain restrictions in my project, I have to use the NOMINMAX define. 
This causes compiler warnings with chaiscript due to the way the following code is structured:

#if defined(CHAISCRIPT_MSVC) && defined(max) && defined(min)
#pragma push_macro("max") // Why Microsoft? why? This is worse than bad
#undef max
#pragma push_macro("min")
#undef min
#endif

If NOMINMAX is used, then the push_macro calls never get made, hence the pop commands are processed with no previous push:

#if defined(CHAISCRIPT_MSVC)
#pragma pop_macro("min")
#pragma pop_macro("max")
#endif

I moved the define check for each min and max around the undef, leaving the push_macro calls to be made regardless.

### Expected Behavior 
No compiler warning

### Actual Behavior 
2x Compiler warning C4602

### Minimal Example to Reproduce Behavior
undef min and max before compiling project with chaiscript

**Comment by lefticus** [comment]
This is actually already fixed on develop branch, I just really-really need to make a release.
