### ISSUE TITLE
Exception thrown on Windows with members (in different classes) of same name

### ISSUE THREAD

**Issue by totalgee** [ChaiScript/ChaiScript#326]
* Compiler Used: Visual Studio 2015
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): x64

I have a ChaiScript program where a "pseudo namespace" (a Dynamic_Object) exposes a member, named "scale".  Another exposed class has a member "scale".  On Windows, when I access the member in the Dynamic_Object, I get an "Exception thrown" message printed (though it must be caught because my program does not crash).  Is this harmless?  Everything seems to return the expected results, apart from these ugly Exception thrown messages (I get a lot in my program).  On OS X (Xcode 8) I get no exceptions or messages.

### Minimal Example to Reproduce Behavior

See [this Gist](https://gist.github.com/totalgee/61a93e646fd349befff62dc54d4c1fca).
```c++
#include <windows.h> // for OutputDebugString()
#include <iostream>
#include "chaiscript/chaiscript.hpp"

using namespace std;
using namespace chaiscript;

struct Test {
    int scale = 3;
};

void bootstrap_Namespace(ChaiScript& chai)
{
    std::shared_ptr<dispatch::Dynamic_Object> nsObj = std::make_shared<dispatch::Dynamic_Object>();
    chai.add_global(var(nsObj), "ns");
    (*nsObj)["func"] = var(fun([](int mult) { return mult + 100; }));
    (*nsObj)["scale"] = var(fun([](int mult) { return mult * 100; }));
}

void Log(string const& str)
{
    OutputDebugStringA((str + "\n").c_str());
}

int main()
{
    ChaiScript chai;
    bootstrap_Namespace(chai);
    chaiscript::utility::add_class<Test>(chai, "Test", {
        constructor<Test()>(),
        constructor<Test(Test const&)>()
    }, {
        { fun(&Test::scale), "scale" }
    });

    // Define a Log() function on Windows rather than just using print(), so 
    // the output shows up in Visual Studio's Debug Output console, alongside
    // the exception message:
    chai.add(fun(&Log), "Log");

    Log("Script starting...");
    chai.eval(R"_(
        Log("Calling ns.func(10): ${ns.func(10)} (all is fine)");
        Log("Calling ns.scale(10): ${ns.scale(10)} -- ns is of type ${ns.get_type_info().name()} (exception thrown)");
        auto t = Test();
        Log("t.scale is ${t.scale} -- t is of type ${t.get_type_info().name()} (all is fine)");
    )_");

    // For me, the script produces the following output (when compiled with
    // https://github.com/ChaiScript/ChaiScript/commit/b7e8897)
    //
    // It produces the right output, but claims to have an exception.  The exception is not "thrown"
    // (to cause the program to crash) in the same way as if there were an error in the script.
    //
    // Script starting...
    // Calling ns.func(10): 110 (all is fine)
    // Exception thrown at 0x00007FFC3A087788 in ChaiWindowsExceptionBug.exe: Microsoft C++ exception: chaiscript::exception::dispatch_error at memory location 0x0000008E93558268.
    // Calling ns.scale(10): 1000 -- ns is of type Dynamic_Object (exception thrown)
    // t.scale is 3 -- t is of type Test (all is fine)
    //

    return 0;
}
```

**Comment by totalgee** [comment]
As mentioned in the code, this happens b7e8897 from Dec. 29, 2016.

**Comment by totalgee** [comment]
Similarly, I get other types of exceptions reported for other reasons.  For example, I get guard_error caught in `dispatch()` (around [line 964 of proxy_functions.hpp](https://github.com/ChaiScript/ChaiScript/blob/develop/include/chaiscript/dispatchkit/proxy_functions.hpp#L964) is where the guard_error exception is caught).  It looks like this is just part of ChaiScript's regular flow of control.  These exceptions are all caught by the code, so I'm not sure why Microsoft C++ insists on logging a message in the debug console for me...  Anyhow, I'm starting to gather these are harmless...correct?

Besides the dispatch_error in the example above (when the same name is found for two different classes), in other cases with my code I'm also seeing:

- chaiscript::exception::guard_error
- chaiscript::detail::exception::bad_any_cast
- chaiscript::exception::bad_boxed_cast

I believe these have to do with a class I'm using with a Vector.   The code appears to work perfectly, I get no crashes, just these messages.

**Comment by lefticus** [comment]
Yes, it's harmless and happens on all platforms. It's partially a side effect of some poor design decisions deep in the core of ChaiScript, and partially a problem with how noisy VS's debugger is on these things.

There is already an issue open #298 which partially addresses this.

I do need to do another audit to see how many more of these it's possible to reduce. 

And if it's any consolation the situation used to be much worse :)

**Comment by totalgee** [comment]
Thanks for the quick answer; that's what I (eventually) figured, that they must be harmless.

**Comment by totalgee** [comment]
Just to add a useful note here...

I eventually discovered that you could turn off the millions of exception messages ChaiScript generates (when debugging in VS) simply by changing a preference in Visual Studio.  In Tools menu -> Options, expand the Debugging node, and click [Output Window](https://docs.microsoft.com/en-us/visualstudio/debugger/output-window-debugging-options-dialog-box).  There you can toggle off "Exception Messages".  You can also do this by right-clicking on the Output Window itself and toggle off Exception Messages there.  Know thy tools!  (-;

Aha -- here are a couple of [SO answers](https://stackoverflow.com/questions/14720599/disable-noise-messages-in-debug-output-windows-visual-studio-2012) that show the interface (it's similar with VS 2015 or 2017).
