### ISSUE TITLE
Question on threading

### ISSUE THREAD

**Issue by Royal-806** [ChaiScript/ChaiScript#331]
I am writing a server and in the server I have a system for completing jobs.
Working something like
```cpp
JobObject doSomething()
{
   chai->eval("blah");
}
addJobToQueue(doSomething);
```
Rather lacking psudocode but when a job is put into the queue it is then picked up by a thread and executed. Any time one of those jobs do ```chai->eval"``` the variables exist on a per thread basis.
so if its ```eval("var two = 2");``` that var only exists on that thread. 
I know that this makes sense with local thread memory but what I need is to be able to access this across the board. 
My question then being, "Am I completely missing some important detail or, am I asking for something I should not?"
Also, do you have any suggestions on how I could achieve what I am doing here or something like it?

**Comment by lefticus** [comment]
If you want to get values out of your thread execution, you could do that be explicitly returning them:

```
auto two = chai->eval<int>("var two = 2; two");
```

Or, if you wanted to extend the lifetime of the object created in the script you could get it back as a `shared_ptr`

```
auto two = chai->eval<std::shared_ptr<int>>("var two = 2; two");
```

On the other hand, if you want to explicitly share between threads, you could do:

```
int two = 2;
chai->add(&two);
chai->eval("two = 3");
```

But keep in mind, if you do the second or third option you are going to have data races and will need to manage your own thread synchronization.

My personal recommendation, and how I prefer to program these days, would be to execute each "eval" inside of a `std::future` then return back the value you calculated / work that was performed.

Then, if you need to have an additional operation on the data, just pass that into the next future.

Does that answer you question?

**Comment by Royal-806** [comment]
Yes, this does answer the question rather thoroughly thank you. 
If possible could recommend an article on std:future and its use? I understand it mostly but I am still unsure on how to properly use it.

**Comment by lefticus** [comment]
I can link you to this: https://www.youtube.com/watch?v=iCL6GYoi1RU which is a video I recorded about `std::future`. Maybe it'll be some help
