### ISSUE TITLE
Chaiscript 6 "unreachable code" with VS2015

### ISSUE THREAD

**Issue by Ybalrid** [ChaiScript/ChaiScript#333]
* Compiler Used: MSVC 14 (Visual Studio 2015)
 * Operating System: Windows 10 
 * Architecture (ARM/x86/32bit/64bit/etc): 64bit
 * Chaiscript 6.0 release 
Hi,

I got this warning (treated as error because /wx) when compiling with /w4 under Visual Studio 2015: 

1>c:\folder\chaiscript\dispatchkit\proxy_functions_detail.hpp(127): error C2220: warning treated as error - no 'executable' file generated
1>c:\folder\chaiscript\dispatchkit\proxy_functions_detail.hpp(127): warning C4702: unreachable code

It looks like the code should disable this specific warning, but apparently it's not the case : 

```c++
#ifdef CHAISCRIPT_MSVC
#pragma warning(push)
#pragma warning(disable : 4702)
#endif
          // MSVC is reporting that this is unreachable code - and it's wrong.
          return Handle_Return<void>::handle();
#ifdef CHAISCRIPT_MSVC
#pragma warning(pop)
#endif
```

It's a minor annoyance, but the fact that the warning wasn't actually disabled here is strange.

**Comment by lefticus** [comment]
It's a known issue that I've discussed with the MSVC team. There's no way to deal with it as far as I know.

**Comment by Ybalrid** [comment]
Okay. Like I said, it's just a minor annoyance ^^"
