### ISSUE TITLE
A global or static instance of chaiscript::ChaiScript crashes the program when it's destroyed.

### ISSUE THREAD

**Issue by p0lszewski** [ChaiScript/ChaiScript#338]
* Compilers Used: G++ version 5.4.0
 * Operating Systems: Linux Ubuntu 16.04
 * Architecture: x86-64
 * ChaiScript version: 6.0.0

A global or static instance of chaiscript::ChaiScript crashes the program when it's destroyed.

### Minimal Example to Reproduce Behavior

```
#include "chaiscript/chaiscript.hpp"

static chaiscript::ChaiScript chai;

int main() {}
```

**Comment by lefticus** [comment]
This is a known issue (although I don't currently see an open bug report for it) that comes down to the `thread_local` stack variables being destroyed before the ChaiScript object is destroyed, it's a C++ linkage thing. Please let me know if you can find a fix for it. If you don't need multithreaded support and must have a global (although I cannot imagine why you must have a global), you can compile with `-DCHAISCRIPT_NO_THREADS`

**Comment by p0lszewski** [comment]
I have a fix, but it leaves a lot to be desired. The only file that required changing was `chaiscript/chaiscript_threading.hpp`. What I do is instead of having static thread_local `std::unordered_map<void *, T>`, I created a new class nested in `Thread_Storage` called simply `Map`, which inherits from `std::unordered_map<void *, T>`. That class has a single boolean member variable called `m_destroyed`, which is set to false in constructor and to true in destructor, and a public method called `destroyed()` for querrying its state. Then, in the destructor of `Thread_Storage`, I modified the removal of `m_key` to happen only on condition of `t().destroyed()` being false. 

It works, at least for me, since there's no segmentation fault anymore, but I am aware that calling methods on an object that's potentially destroyed is undefined behavior. Even so, since static thread_local variables are statically allocated, there's a good guarantee that the memory where the object resided will still be valid and unchanged even after its destructor has been called, and I would say that a potential crash is still better than a certain one.

You can see the exact changes [here](https://github.com/p0lszewski/ChaiScript/blob/safe_global_and_static_instances/include/chaiscript/chaiscript_threading.hpp), I'm reluctant to open a pull request because of the reasons specified above, but I will use this version for my purposes.

**Comment by lefticus** [comment]
I think I might have a slightly better idea, I'm going to see if I can come up with something. Some way of guaranteeing the lifetime of the thread_local will be > then containing object.

**Comment by lefticus** [comment]
I built on your idea, but I think I made it more guaranteed.
