### ISSUE TITLE
Allow use of "this" in lambda capture

### ISSUE THREAD

**Issue by totalgee** [ChaiScript/ChaiScript#341]
* Compiler Used: Xcode 8.2.1
 * Operating System: OS X 10.11.6
 * Architecture (ARM/x86/32bit/64bit/etc): MacBook Air
 
### Expected Behavior 

Allow capturing "this" when in a member function of a class/type defined in ChaiScript.

### Actual Behavior 

Error is thrown: "Name already exists in current context this"

### Minimal Example to Reproduce Behavior

```
class Test {
    auto value;
    auto lambda;
    
    def Test() {
        this.value = 5;
        this.lambda = fun[this]() {
            print("I'm in the lambda with value ${this.value}");
        }
    }
};

auto t = Test(); // throws "Name already exists in current context this"
t.lambda();
```

And here is an example (workaround) that works, assigning `this` to a different variable:

```
class Test {
    auto value;
    auto lambda;
    
    def Test() {
        this.value = 5;
        auto& obj = this;
        this.lambda = fun[obj]() {
            print("I'm in the lambda with value ${obj.value}");
        }
    }
};

auto t = Test();
t.lambda();  // works: I'm in the lambda with value 5
```

**Comment by lefticus** [comment]
I thought I already fixed this before 6.0 was released?

**Comment by totalgee** [comment]
Okay, I'll check with a more recent version, sorry, I'm still on my "new year's" version, more or less...

**Comment by lefticus** [comment]
I was just confused for a moment. It's possible I missed something.

**Comment by totalgee** [comment]
Just tested this with 0f9d9ca (the latest) on develop branch, and indeed my first example works fine capturing `this` directly.  Sorry for the noise!

I'll upgrade my project to the latest version...or at least v6.0.

**Comment by lefticus** [comment]
No problem, sorry about the confusion.
