### ISSUE TITLE
No bitwise operator

### ISSUE THREAD

**Issue by bkeys** [ChaiScript/ChaiScript#342]
* Compiler Used: gcc
 * Operating System: Fedora 25
 * Architecture (ARM/x86/32bit/64bit/etc):  all
 

### Expected Behavior 
There to be one
### Actual Behavior 
There was none
### Minimal Example to Reproduce Behavior
Try to use the bitwise operator, it is not there

**Comment by lefticus** [comment]
Please provide an example of what you are trying to do. There are many bitwise operators and they are tested here:

https://github.com/ChaiScript/ChaiScript/blob/develop/unittests/operators_int.chai

**Comment by bkeys** [comment]
You are right this works.
