### ISSUE TITLE
How to declare global variables for scripts?

### ISSUE THREAD

**Issue by bkeys** [ChaiScript/ChaiScript#343]
I am trying to figure out how to (from within chaiscript) declare a global variable, within a loop. So lets say I have a script in my game that is being executed every frame, then I cannot simply do

`var i`

because then I would get an error about a redeclaration of the variable, this also follows through for functions. I could simply have a decl.chai script for declarations, interpret them once on initialization and then move forward that way. I would like to know beforehand if that is the intended way for chaiscript to be used, or is there some functionality for this somewhere that I am mising?

**Comment by lefticus** [comment]
There's an open issue for the ability to reload scripts without getting a redeclaration error, but I'd be surprised if what you actually want is to reload the script on *every frame*.

More likely, you want to execute the script once, which will create some function, then call that function on each frame?

If you want an actual global to be created, you can use the keyword `global` https://github.com/ChaiScript/ChaiScript/blob/develop/cheatsheet.md#variables

if you want a locally scoped variable that doesn't get redefined on each script execution, you might want to put it in a scope, just like you would in C++:

```
{
  var some_variable = 2;
}
```

**Comment by bkeys** [comment]
Yes but my reasoning for running the script each frame is, that if I were to only interpret the script once, then scripts become essentially useless after they get used once. Furthermore, if I have other logic going on in a given frame of the game, all of it would have to be done in chaiscript which is not all that practical.

**Comment by lefticus** [comment]
No, parse one, interpret many times. Plus, it is trivially easy to do:

```cpp
/* some C++ logic */
chai.eval("someFunctionIKnowTheNameOfFromAScript()");
// or
someFunctionObjectThatCameFromScript()
/* other c++ logic */
```

But you can do as you choose.

Either way, you can declare a global or you can use a local scope around the variable in the script.
