### ISSUE TITLE
Any support for [] operators?

### ISSUE THREAD

**Issue by bkeys** [ChaiScript/ChaiScript#344]
I am trying to register a std::map and an std::array in chaiscript, but am not really seeing any examples on how to do such. Is there any way to register and use these containers in chaiscript?

**Comment by lefticus** [comment]
`operator[]` works like any other operator in ChaiScript. 

Regarding `std::vector` and `std::map` that is how the build int Vector and Map types in ChaiScript are implemented. They are direct mappings of `std::vector<Boxed_Value>` and `std::map<std::string, Boxed_Value>`. If you want to add your own versions of these containers you can easily do that with the helpers that are already provided. See here for an example of how to use the helpers: https://github.com/ChaiScript/ChaiScript/blob/develop/include/chaiscript/chaiscript_stdlib.hpp#L50-L53
