### ISSUE TITLE
Unsure of use

### ISSUE THREAD

**Issue by Royal-806** [ChaiScript/ChaiScript#346]
I am not clear on how to best go about this but,
I have an entity / component set up. 
I would like to have a base "script" component that defines some behavior functions

How could this be achieved?
I was thinking inheritance but I am not sure if chai classes can inherit.
I am at a loss on how to continue.

**Comment by lefticus** [comment]
Chai classes do not support inheritance, but you could pass in a map object that has default properties implemented, then reassign the ones you want to override in your "derived" script.

**Comment by RobLoach** [comment]
Feel free to create an issue over at the Discourse. There was a quick question over at http://discourse.chaiscript.com/t/class-inheritance/101 .
