### ISSUE TITLE
Explore def-use analysis for easy optimization of lookups

### ISSUE THREAD

**Issue by jonathandturner** [ChaiScript/ChaiScript#35]
We should be able to speed up variable lookup dramatically in some cases by caching the def of identifiers we know statically at parse time.  It may be as simple as a double-pointer to the currently definition of the variable (def's of variables aren't unique based on AST location, as in the case of var decls inside of loops).

**Comment by lefticus** [comment]
Offset code working on c7689f18ec8043caef89f93374145a8e2c9c2ad5
