### ISSUE TITLE
Error construct class Fl_Window from chaiscript string

### ISSUE THREAD

**Issue by dmxvlx** [ChaiScript/ChaiScript#353]
* Compiler Used: GCC-4.9.3
 * Operating System: Linux
 * Architecture (Core i5, 64bit): 
 

I want register class Fl_Window and some its funcmembers in the chai engine,
and show window from evaluating of chai script string from my c++ programm.

But I got error:
[ERROR]
terminate called after throwing an instance of 'chaiscript::exception::eval_error'
  what():  Error: "Error with function dispatch with function 'Fl_Window'" With parameters: (const int, const int, const string)
[/ERROR]

from calling this code:
[CODE]
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Window.H>

#include <iostream>

#include <chaiscript/chaiscript.hpp>
#include <chaiscript/dispatchkit/bootstrap_stl.hpp>
#include <chaiscript/dispatchkit/function_call.hpp>
using namespace chaiscript;

// g++ -std=c++14 chai_fltk.cxx -o chai_fltk $(fltk-config --use-images --ldflags) && ./chai_fltk
int main(){
  
  chaiscript::ChaiScript chai;
  
  chai.add(chaiscript::fun(static_cast<void(Fl_Window::*)()>(&Fl_Window::end)), "end");
  chai.add(chaiscript::fun(static_cast<void(Fl_Window::*)()>(&Fl_Window::show)), "show");
  chai.add(chaiscript::constructor<Fl_Window (const int,const int,const char*)>(), "Fl_Window");
  
  chai.add(chaiscript::base_class<Fl_Widget, Fl_Group>());
  chai.add(chaiscript::base_class<Fl_Group, Fl_Window>());
  chai.add(chaiscript::base_class<Fl_Window, Fl_Double_Window>());
  chai.add(chaiscript::user_type<Fl_Widget>(), "Fl_Widget");
  chai.add(chaiscript::user_type<Fl_Group>(), "Fl_Group");
  chai.add(chaiscript::user_type<Fl_Window>(), "Fl_Window");
  chai.add(chaiscript::user_type<Fl_Double_Window>(), "Fl_Double_Window");
  
  chai.add(chaiscript::user_type<Fl>(), "Fl");
  chai.add(fun(Fl::run), "run");
  
  std::string script = R""(
    var win = Fl_Window(200, 200, "window"); // new Window
    win.end();
    win.show(); // show the Window
    run(); // event loop of FLTK
    )"";
    
    chai.eval(script);
  
  return 0;
}
[/CODE]

--
Thanks.

**Comment by lefticus** [comment]
Same as C++ - no automatic conversion from `string` to `const char *`. You need to call `"Fl_Double_Window".c_str()` or modify your interface to take a `const std::string &`.

**Comment by dmxvlx** [comment]
Thanks !

I have found this:

[CODE]
chai.add(chaiscript::type_conversion<const std::string, const char*>([](const std::string t_bt) { return (const char*)t_bt.c_str(); }));
[/CODE]

And it's works !

Is that right ?

**Comment by lefticus** [comment]
Yes, that can work also.
