### ISSUE TITLE
Equality between Boxed_Value

### ISSUE THREAD

**Issue by SquallChua** [ChaiScript/ChaiScript#354]
Hi,

I am wondering if there is any simple way to test for equality between Boxed_Value.
As I can't seem to find any existing operator/function that may do the job.

**Comment by lefticus** [comment]
The problem is that `Boxed_Value` objects may be of two completely different types internally which may not be comparable at all.

You could do something like this:

```cpp
// capture dynamically dispatched operator `==`
auto equality = chai.eval<std::function<bool (const chaiscript::Boxed_Value &, const chaiscript::Boxed_Value &)>>("`==`");

// execute it:
try {
  if (equality(bv1, bv2)) {
    // they were comparable and are ==
  } else {
    // they were comparable and are not ==
  }
} catch (const chaiscript::eval_error &ee) {
  // they were not comparable 
}
```
