### ISSUE TITLE
Performance cost of creating a variable is very high

### ISSUE THREAD

**Issue by markusobi** [ChaiScript/ChaiScript#356]
* Compiler Used: gcc
 * Operating System: Ubuntu
 * Architecture: x86_64
 * Chaiscript version 6.0.0
 * `Release` configuration with `MULTITHREAD_SUPPORT_ENABLED = False`
 * CPU: i5-2500 3.3-3.7 Ghz

I was looking for a scripting language for a game (details on bottom), so I tried to measure the performance of basic operations in Chaiscript. I benchmarked calling empty functions and adding the numbers from 1..N. I know that Chaiscript is not designed/optimized for this cases. Performance results were not really staggering, but acceptable, _until_ I had a benchmark which created a variable.
```
def var_test(int n)
{
    for (var i = 0; i < n; ++i)   {
        var j = 0
    }
}

def sum_test(int n)
{
    var sum = 0;
    for (var i = 0; i < n; ++i)   {
        sum += i
    }
    return sum
}

var n = 1000000
var_test(n) // takes 2.6 s
sum_test(n) // takes 0.24 s
```
**Creating a variable is abysmally slow to the point, that it becomes the performance bottleneck**. Any insight in why this is such an expensive operation?

To estimate the time it would take when using Chaiscript in REGoth, I measured the number of variable declarations and the highest value I could find was about 350 declarations per frame (this number might be much higher when using mods). Our Daedalus VM (which is not optimized at all) took about `0.2 ms` to execute all the code. The declarations of `350` variables alone would take roughly `1 ms` with Chaiscript. That's five times as much without even considering the time for the actual code.

About REGoth:
I am currently looking for a replacement for the scripting language (Daedalus) of the [REGoth](https://github.com/REGoth-project/REGoth) project (reimplementation of Gothic I&II). Daedalus is the original scripting language of Gothic I & II and is very limited language wise. We are currently using a simple bytecode VM, which executes the compiled Daedalus-bytecode. We have the source code of the Scripts, so we could transform the Daedalus code to any other scripting language. In the game each NPC is in a certain state and in each frame a state-specific script-function is executed for each NPC. These calls make up the majority of the script-calls.

**Comment by lefticus** [comment]
I'm looking at this issue now and attempting to optimize it. I have currently gotten this specific test cast to be about 6x faster. 

However, while working on this I've noticed that I've now reached the point where it would be possible for me to completely remove, during parse-time optimizations, the unused variable declaration, making the entire test runtime go to near-0.

I'm not going to implement that right now, but I am curious what your thoughts on it are, if any.

**Comment by markusobi** [comment]
Thank you for your response!
Factor 6 performance improvement sounds very promising.

My testing case is flawed in this concern, because a compiler may remove the declaration (as you said), because it has no _observable side effects_. I didn't bother inserting a dummy use, because I saw that the compiler wouldn't remove it anyway (by looking at the performance numbers).
Dead-code elimination is a nice transformation to have in general (though I expect to it not occur very often in real world applications). If it's not much effort to do it, there is no reason not to do it.

Nevertheless, as soon as this optimization kicks in, one has to tweak the test-case to prevent the compiler from removing the code.

The key really is to do as much work as possible at parse-time.
The **big** obstacle for optimization transformations really is the `eval` function. I am curious how you handle these? As soon as there is one `eval` in a function you can't really rely on anything anymore.

I remember implementing SSA-trafo/variable-lifetime-analysis/dead-code-elimination/const-propagation for a statically typed c-subset. How do you handle `eval` when doing optimizations?

**Comment by lefticus** [comment]
There are many optimizations that I don't do yet (for example inlining) because of the possibility of the behavior being modified at runtime with a new overload being added. 

Most of my optimizations and transformations are AST simplifications which can have a huge impact by eliminating things like unnecessary `return` statements, variable scopes and constant folding.

And because in ChaiScript and `eval` is going to execute in its own function-like context with its own stack, that isn't a problem for us.

**Comment by ciplogic** [comment]
I don't want to be "that guy" but there was in the past an issue about using bytecode interpreter.

I know I may sound annoyingm but as @markusobi was commenting: "I remember implementing SSA-trafo/variable-lifetime-analysis/dead-code-elimination/const-propagation for a statically typed c-subset." 

And this is not only about inlining (or CSE) which are easier to be interpreted on a bytecode, but interpretation is quicker against a bytecode: you have a big switch which advances based on instruction is current.

I have been also implementing a similar to SSA form for .Net bytecode and I found that are many optimizations you can do decently easy only on a bytecode. For example: LICM (moving "static" code outside of loops) is very easy to do it canonically on a "CFG" or any form of bytecodes, and is very ugly to do it on an AST.

**Comment by markusobi** [comment]
I did a benchmark by comparing [v6.1.0](https://github.com/ChaiScript/ChaiScript/tree/v6.1.0) vs https://github.com/ChaiScript/ChaiScript/commit/ea03a5462f0a9edfc07c536d540ba9c1e66307e9.

Basically testing
```
for (var i = 0; i < n; ++i)
{
    sum += i
}
```
vs

```
for (var i = 0; i < n; ++i)
{
    var dummy1 = 0;
    sum += i
}
``` 
for n=1000000
[full scripts](https://github.com/markusobi/ChaiScript-Example/blob/master/scripts/)

Here are the results:
> ea03a5462f0a9edfc07c536d540ba9c1e66307e9:
> interpreting ./scripts/sum.chai: **290.902** milliseconds
> interpreting ./scripts/variable_declaration.chai: **3635.35** milliseconds
> 
> v6.1.0
> interpreting ./scripts/sum.chai: **290.49** milliseconds
> interpreting ./scripts/variable_declaration.chai: **683.807** milliseconds

Performance penalty when adding a declaration statement went from factor ~13 to factor ~2.
For me this issue is resolved.

[build & benchmark script](https://github.com/markusobi/ChaiScript-Example/blob/master/bench.sh).
Platform: Windows 64bit
Config: Release
threads: CHAISCRIPT_NO_THREADS

**Comment by RobLoach** [comment]
Thanks for going through the performance testing on this. Very informative, and good to see measurable results.
