### ISSUE TITLE
Buck build support

### ISSUE THREAD

**Issue by njlr** [ChaiScript/ChaiScript#358]
* Compiler Used: Clang
 * Operating System: macOS
 * Architecture (ARM/x86/32bit/64bit/etc): 64bit
 
I would be fantastic if ChaiScript could provide [Buck build](https://buckbuild.com/) support. This would allow ChaiScript to be part of fast, reproducible builds out-of-the-box. 

### Expected Behavior 
N/A new feature

### Actual Behavior 
N/A new feature

### Minimal Example to Reproduce Behavior
N/A new feature

**Comment by lefticus** [comment]
Accepted #359
