### ISSUE TITLE
ChaiScript lambda function conversion to std::function

### ISSUE THREAD

**Issue by stephenberry** [ChaiScript/ChaiScript#360]
* Compiler: MSVC 2015
 * Operating System: Widows 10
 * Architecture:  x64
 
Example of working conversion:  
``` C++
void evaluator(const std::function<void(const double x)>& func, const double x)
{
   func(x);
}

int main()
{
   chaiscript::ChaiScript chai;

   chai.add(chaiscript::fun(&evaluator), "evaluator");
   ...
```
Script:
```
auto y = 5.0
auto func = fun[y](x)
{
	y += x
}
evaluator(func, 2.0)
print(y)
```
Output: 7

This all works great, but if I change the `evaluator` method to take a non const reference to a std::function, then I get: "Error with function dispatch with function `evaluator`" ...

Breaking `evaluator` function:
``` C++
void evaluator(std::function<void(const double x)>& func, const double x)
{
   func(x);
}
```

So, the implicit conversion fails. This is not necessarily a bad restriction, as the input function should probably be const qualified in most use cases. However, I wanted to point this out in case you weren't aware. And, if this restriction is kept, it would be nice to have a more detailed error description, which hinted that the conversion to std::function must be const qualified.

**Comment by lefticus** [comment]
It's (almost) impossible for me to allow a non-const reference here, as it would require some meaningful way of communicating the changes to the `std::function` object back to the ChaiScript engine.

By "impossible" I mean it would take considerable and expensive reworkings of the internals of how functions are handled internally.
