### ISSUE TITLE
MSVC does not compile stdlib example, and crashes with .add(stdlib)

### ISSUE THREAD

**Issue by NiklasRosenstein** [ChaiScript/ChaiScript#364]
* Compiler Used: MSVC 19.10.25019 for x64
 * Operating System: Windows10
 * Architecture (ARM/x86/32bit/64bit/etc):  64-bit

The example with using the standard library compiled into the same executable/shared library uses the following code:

```
  chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());
```

However, this does not compile.

```
cmd /Q /c .commands\chaic4d-1.0.0.objects.cmd "c:\users\niklas\applications\cinema 4d r18.057\plugins\chaic4d\src\main.cpp" "c:\users\niklas\applications\cinema 4d r18.057\plugins\chaic4d\build\chaic4d-1.0.0\obj\src\main.obj"
c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include\xlocale(314): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
c:\users\niklas\applications\cinema 4d r18.057\plugins\chaic4d\src\main.cpp(9): error C2664: 'chaiscript::ChaiScript::ChaiScript(const chaiscript::ChaiScript &)': cannot convert argument 1 from 'chaiscript::ModulePtr' to 'std::vector<std::string,std::allocator<_Ty>>'
        with
        [
            _Ty=std::string
        ]
c:\users\niklas\applications\cinema 4d r18.057\plugins\chaic4d\src\main.cpp(9): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

I tried using `.add()` instead, but it leads to a crash.

```
  chaiscript::ChaiScript chai;
  chai.add(chaiscript::Std_Lib::library());
```
 
![image](https://user-images.githubusercontent.com/1318438/29497287-e3484ba2-85e5-11e7-8bb1-49b1975f0135.png)

> Unhandled exception at 0x00007FFD5B267788 in CINEMA 4D.exe: Microsoft C++ exception: std::system_error at memory location 0x000000783431B720.

**Comment by lefticus** [comment]
It sounds like you are using ChaiScript 6, but following an example from pre version 6. Please link me to which example you are using so I can correct that.

if you just do:

```cpp
chaiscript::ChaiScript chai;
```

It will compile in the stdlib as you want.

I should also note that I think you have an error in your Visual Studio setup, as you are getting this warning also:

```
C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
```

ChaiScript absolutely requires that exceptions be enabled.

-Jason

**Comment by lefticus** [comment]
Closing for lack of updates.

**Comment by NiklasRosenstein** [comment]
Sorry for the lack of feedback. Just using `chaiscript::ChaiScript chai;` works like a charm.

Compiled with Visual Studio 2017, FYI. I read that some people have issues with VS 2017 in Gitter, but I don't have them. (I didn't use CMake though).

Cheers!
