### ISSUE TITLE
from_json uses "long", compiles as 32 bit int on Windows vs 64 bit int on Linux

### ISSUE THREAD

**Issue by dinghram** [ChaiScript/ChaiScript#368]
* Compiler Used: Visual Studio 2015 Update 3
 * Operating System: Windows (any)
 * Architecture (ARM/x86/32bit/64bit/etc): 64bit
 

### Expected Behavior 
Invoke from_json with integer too big to fit in 32 bit integer succeeds, returning an int64.

### Actual Behavior 
Invoke from_json with integer too big to fit in 32 bit integer overflows the integer and returns an incorrect value.

### Minimal Example to Reproduce Behavior
print( from_json( "100000000000" ) );

**Comment by dinghram** [comment]
Suggested fix:
[json.zip](https://github.com/ChaiScript/ChaiScript/files/1318213/json.zip)

**Comment by lefticus** [comment]
Can you submit it as a pull request please?
