### ISSUE TITLE
from_json gives incorrect result when float value has negative exponent

### ISSUE THREAD

**Issue by totalgee** [ChaiScript/ChaiScript#376]
* Compiler Used: Xcode 9
 * Operating System: macOS 10.12.6
 * Architecture (ARM/x86/32bit/64bit/etc): x64

### Expected Behavior 

`from_json("35.2e-2")` should give 0.352, but gives 35.2.

### Actual Behavior 

When there is a negative exponent on a JSON-parsed number, it always returns the exponent 0, because parse_num<long> doesn't support negative numbers.  The solution will be to fix only the JSON parsing code, because it's too risky to touch the low-level ChaiScript number parsing! (I tried once before ;-)

### Minimal Example to Reproduce Behavior

```
// These all fail as unit tests
assert_equal(from_json("9.9e-02"), 9.9e-02)
assert_equal(from_json("1E-01"), 0.1)
assert_equal(from_json("-314159e-5"), -3.14159)
```

**Comment by lefticus** [comment]
Merged. Thanks for the patch. Ultimately I need to just unify the JSON number parser and the ChaiScript number parser if possible, but I think they have slightly different formats.
