### ISSUE TITLE
ChaiScript scalability

### ISSUE THREAD

**Issue by Mellnik** [ChaiScript/ChaiScript#379]
* Compiler Used: GCC,MSVC
 * Operating System: Linux,Windows
 * Architecture (ARM/x86/32bit/64bit/etc):  x64
 
Hi all,
I am currently evaluating which scripting language fits the most for my project. ChaiScript looks promising.
The only thing I am concerned about is ChaiScript scalability. Can it handle these points and still be quite fast?

- A single ChaiScript file with over 100,000 lines.
- 2000 unique ChaiScript functions, half of them being called by C++
- 500 C++ functions exposed to ChaiScript
- 500 global variables
- Script will be compiled once and then runs continuously for several months in memory without a restart!
- The script will mostly consist of loops, calling other functions and rarely heavy computations.

No thread safety is required, I have already disabled it. Maybe you have made some experiences with very large scripts or know some other project using ChaiScript at a large scale.

Thanks!

**Comment by lefticus** [comment]
All I can say is give it a try and see what happens. I don't have any experience at that scale. Create a new issue if you have problems that can be reproduced. 

Thanks!
