### ISSUE TITLE
to_json does not convert null values

### ISSUE THREAD

**Issue by arcoRocks** [ChaiScript/ChaiScript#381]
* Compiler Used: Microsoft Visual C++ 2017
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): 32/64
 * Branch: release-6.x
 

### Expected Behavior 
```
to_json(from_json("{\"a\": \"string\", \"b\": null}"))
{
  "a" : "string",
  "b" : null
}
```
### Actual Behavior 
```
 to_json(from_json("{\"a\": \"string\", \"b\": null}"))
Unknown object type to convert to JSON
```

**Comment by RobLoach** [comment]
I think this is done?
