### ISSUE TITLE
/Wall Warnings

### ISSUE THREAD

**Issue by shockdot** [ChaiScript/ChaiScript#384]
* Compiler Used: VS 2017
 * Operating System: Windows 7
 * Architecture (ARM/x86/32bit/64bit/etc):  x64
 

### Expected Behavior 
Clean Compile when I try to compile with /Wall and errors on warning enabled.

### Actual Behavior 
Thousands of warnings

### Minimal Example to Reproduce Behavior
Make a new C++ project, enable /Wall, enable errors on warnings for the project.
Include chaiscript
Compile (no code needed)
You get thousands of warnings...

Are there any plans to appease the warnings?

**Comment by lefticus** [comment]
No, it is impossible to compile with `/Wall` on MSVC because the Windows and standard library headers themselves do not compile cleanly with `/Wall`, and we rely on the standard library and some operating system calls.

**Comment by lefticus** [comment]
Example compiler explorer link for why this is impossible: https://godbolt.org/g/fLD5MF

**Comment by shockdot** [comment]
Okay thanks, I ended up silencing the warnings.
