### ISSUE TITLE
Build Process?

### ISSUE THREAD

**Issue by Nachtfeuer** [ChaiScript/ChaiScript#386]
Hi lefticus,

have seen you in Berlin listening to your talks. Have been great.
That was also the reason to investigate a bit into chaiscript :)

I have a few notes on the build process since I have not found details in the documentation.
At least I have been reading that the code is header only, c++1y and the dl library is needed.

I'm also using a CMake based build process.

Usually I install dependencies like boost via package manager. I guess chiascript will not be available soon, right?.

So one solution (for my internal test) was to download the zip you have provided in the release tab.
I managed it with `files(DOWNLOAD ...)` and `add_custom_target` to have chaiscript under ${CMAKE_BINARY_DIR}/includes. With `include_directories(${PROJECT_NAME} ${CMAKE_BINARY_DIR}/includes)` the rest works fine.

Also to note about compiler warnings ... using `-Weffc++` throws a lot warnings related
to chiascript. Is there a way to suppress that explicitely for chiascript?

Anyway the zip contains a lot more ... there's is no header only distribution, right?

It would be great to see an example in your doc on how you would advise to
integrate chaiscript with cmake.

Finally ... small note on `chaiscript::var` ... I wonder that it allows to change a variable (write) within a script but a change from outside does not affect the script ... as an example those work

        int n = 2;
        chai.add(chaiscript::var(n), "n");
        REQUIRE(chai.eval<bool>("isPrime(n) && (n == 2)") == true);
        n = 3;
        chai.add(chaiscript::var(n), "n");
        REQUIRE(chai.eval<bool>("isPrime(n) && (n == 3)") == true);

I assumed that second call to "add" is not necessary but ... it is ... at least the REQUIRE fails if I miss it.

That's all

Regards,
Thomas

**Comment by lefticus** [comment]
I think most users either make ChaiScript a submodule of their git project or they user cmake's `ExternalProject_add` feature. There's probably also many who just copy the headers into their project, but I'm not sure I'd recommend that option.

There is support for buckaroo build system / packages currently on develop, but support for other package managers is always welcome.

I don't currently try to build cleanly with `-Weffc++`. I have not found the flag to be useful to leave on all the time. There are too many warnings that are just guidance and don't help the overall quality of code.

for example, this warning:

```
include/chaiscript/dispatchkit/dynamic_object.hpp:51:9: warning: ‘chaiscript::dispatch::Dynamic_Object::m_attrs’ should be initialized in the member initialization list [-Weffc++]
         Dynamic_Object() = default;
         ^~~~~~~~~~~~~~
```

Is terrible. This would make code quality significantly worse. It is clear that the gcc developers have not been updating the flag to take into account changes in C++11 and forward.

Regarding `chaiscript::var`, this makes a copy by default (if it took a reference by default there'd be no way to explicitly make a copy) so to do what you want you'd want to:

```cpp
int n = 2;
chai.add(chaiscript::var(&n), "n"); // note the & dereferencing
REQUIRE(chai.eval<bool>("isPrime(n) && (n == 2)") == true);
n = 3;
REQUIRE(chai.eval<bool>("isPrime(n) && (n == 3)") == true);
```

**Comment by lefticus** [comment]
Also, the warning flags that I do currently compile with are:

```
-Wall -Wextra -Wconversion -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wcast-qual -Wunused -Woverloaded-virtual  -pedantic
```

**Comment by Nachtfeuer** [comment]
Great, thanks
