### ISSUE TITLE
Will Chaiscript do JIT?

### ISSUE THREAD

**Issue by patlecat** [ChaiScript/ChaiScript#389]
Quick question thrown in just to see where this is going and what we can expect. Can you please elaborate on what the reasons for both cases are?

**Comment by ciplogic** [comment]
I am not a developer, but I think that a JIT will never be the case. Not for other reason that there is arguably relatively a lot of work with very little benefit. 

Most of your code would run in C++ anyway as C++ is the hosting language.

I can assume there could be portable ways to do improvements, like using an optimizing bytecode interpreter (what PHP did for their Zend higher tier interpreter for many years), but this work still is a large item which I would assume no one would take it soon.

**Comment by lefticus** [comment]
JIT will never happen, it would cause too many portability issues and largely change the nature of chaiscript entirely. Bytecode is a very remote possibility.
