### ISSUE TITLE
Compilation error with Visual Studio 2017 update 5

### ISSUE THREAD

**Issue by runarundheim** [ChaiScript/ChaiScript#390]
* Compiler Used: Visual Studio 2017 Update 5
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc):  64 bit
 

### Expected Behavior 
Code should compile

### Actual Behavior 
Compiler error:
1>------ Build started: Project: ChaiScript, Configuration: Debug x64 ------
1>ChaiScript.cpp
1>s:\chaiscript-6.0.0\include\chaiscript\language\chaiscript_eval.hpp(306): error C2760: syntax error: unexpected token '>', expected 'expression'
1>s:\chaiscript-6.0.0\include\chaiscript\language\chaiscript_eval.hpp(306): note: This diagnostic occurred in the compiler generated function 'chaiscript::Boxed_Value chaiscript::eval::Fun_Call_AST_Node<T>::do_eval_internal(const chaiscript::detail::Dispatch_State &) const'
1>s:\chaiscript-6.0.0\include\chaiscript\language\chaiscript_eval.hpp(336): note: see reference to class template instantiation 'chaiscript::eval::Fun_Call_AST_Node<T>' being compiled
1>Done building project "ChaiScript.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

### Minimal Example to Reproduce Behavior
#include <chaiscript/chaiscript.hpp>

int main()
{
  return 0;
}

**Comment by runarundheim** [comment]
https://developercommunity.visualstudio.com/content/problem/167061/not-possible-to-compile-with-chaiscript-600.html

**Comment by lefticus** [comment]
FYI I have tried many times to reproduce this error and cannot. I have no problem compiling ChaiScript 6.0 on VS2017, with any update level I've tried.

**Comment by lefticus** [comment]
I also just got confirmation from another user that he had to reinstall visual studio 2017 for some unknown reason, but once he did it worked fine with ChaiScript.

**Comment by DexterHaslem** [comment]
Just to add a datapoint, I am on a fresh install of the latest vs2017 and I get a slightly different error on the same line:

    ... chaiscript-6.0.0\include\chaiscript\language\chaiscript_eval.hpp(306): error C2760: syntax error: unexpected token 'const', expected 'expression'

However, in the bug report thread above, they said it has been fixed pending release, so I'll probably just wait for that to use Chaiscript 6!

**Comment by runarundheim** [comment]
Fixed by Microsoft in version 15.6.0 preview 2. Seems that solution #395 also fix the compilation in version 15.5.x.
