### ISSUE TITLE
mixing strings and integers (chaiscript 6.0.0)

### ISSUE THREAD

**Issue by olikraus** [ChaiScript/ChaiScript#401]
* Compiler Used: g++
 * Operating System: Windows, MinGW
 * Architecture (ARM/x86/32bit/64bit/etc):  x86/64bit
 

### Expected Behavior 
```
var a = 123; var b = "45";
if ( to_int(a) > to_int(b) )       // this should be "true"
```
### Actual Behavior 
```
var a = 123; var b = "45";
if ( to_int(a) > to_int(b) )       // Error thrown by parser
```

### Minimal Example to Reproduce Behavior
```
var a = 123; var b = "45";
print( to_int(a) > to_int(b) )       // this should print "true", instead parser throws an error
```

### Suggestion
Add
```
def to_int(int a) { return a; }
```
to the build-in functions.

### Discussion
 * This behavior is inconsistent, because "print( to_string(a) > to_string(b) )" will work as expected (and will obviously will return "false")
 * Nevertheless, this is not a bug, so rejecting this issue would be ok for me.

**Comment by lefticus** [comment]
I agree, I added the overloads in this commit 6c41ac90d84a37fb0f3c1dfb4c3bf2646644d19c

**Comment by olikraus** [comment]
Thanks!
