### ISSUE TITLE
user literals for numeric types

### ISSUE THREAD

**Issue by cszawisza** [ChaiScript/ChaiScript#406]
Hi!

This is only a question.
Is there a way to add own literals for numeric types? as in [C++](http://en.cppreference.com/w/cpp/chrono/operator%22%22ms)
e.g.
`var time = 10h`

**Comment by lefticus** [comment]
No, not currently. And unlikely to ever be supported, given the difficulty it causes in C++ for parsing and execution.

you could expose a function like `h` so you get `h(10)` or probably best would be `hour(10)`.
