### ISSUE TITLE
error C2760: syntax error: unexpected token 'const', expected 'expression'

### ISSUE THREAD

**Issue by jeanga** [ChaiScript/ChaiScript#412]
* Compiler Used: Visual Studio 2017 V15.5.6
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): 64bits
 
While compiling the sample from main page of http://chaiscript.com/...
Using chaiscipt installed via vcpkg (https://github.com/Microsoft/vcpkg)

### Expected Behavior 

Compiles and runs!

### Actual Behavior 
`1>d:\vcpkg\installed\x64-windows\include\chaiscript\language\chaiscript_eval.hpp(306): error C2760: syntax error: unexpected token 'const', expected 'expression'
1>d:\vcpkg\installed\x64-windows\include\chaiscript\language\chaiscript_eval.hpp(306): note: This diagnostic occurred in the compiler generated function 'chaiscript::Boxed_Value chaiscript::eval::Fun_Call_AST_Node<T>::do_eval_internal(const chaiscript::detail::Dispatch_State &) const'
1>d:\vcpkg\installed\x64-windows\include\chaiscript\language\chaiscript_eval.hpp(336): note: see reference to class template instantiation 'chaiscript::eval::Fun_Call_AST_Node<T>' being compiled
`

### Minimal Example to Reproduce Behavior

`#include <chaiscript/chaiscript.hpp>

std::string helloWorld(const std::string &t_name) {

	return "Hello " + t_name + "!";

}

int main() {

	chaiscript::ChaiScript chai;
	chai.add(chaiscript::fun(&helloWorld), "helloWorld");
	chai.eval(R"(
    puts(helloWorld("Bob"));
  )");

}
`

**Comment by lefticus** [comment]
I had no idea ChaiScript was on VCPKG!

But anyhow, you either have to *not* use `c++latest` or you need to use the latest from git develop branch to work on the latest builds of VS.

**Comment by jeanga** [comment]
Hi !

I got the same error message with « ISO C++14 Standard (/std:c++14) » (with the vcpkg port, did not try the latest and greatest from the dev branch… yet).

Thanks for the quick answer.

Jean

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Jason Turner<mailto:notifications@github.com>
Envoyé le :Friday, February 16, 2018 4:06 PM
À : ChaiScript/ChaiScript<mailto:ChaiScript@noreply.github.com>
Cc : jeanga<mailto:jeanga@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [ChaiScript/ChaiScript] error C2760: syntax error: unexpected token 'const', expected 'expression' (#412)


I had no idea ChaiScript was on VCPKG!

But anyhow, you either have to not use c++latest or you need to use the latest from git develop branch to work on the latest builds of VS.

**Comment by lefticus** [comment]
Closing, with no way to reproduce with official releases.
