### ISSUE TITLE
Unicode escapes in string literals are wrong and don’t support UTF-32

### ISSUE THREAD

**Issue by chris0e3** [ChaiScript/ChaiScript#415]
* Compiler Used: Clang 4.0.1
 * Operating System: OSX
 * Architecture (ARM/x86/32bit/64bit/etc): x86-64
 
eval> `["Test\u20Me", "Test\u2022Me"]`
eval> `"Test\U1F534Me"`

### Expected Behavior 
`[Test Me, Test•Me]`
`Test🔴Me`

### Actual Behavior 
`[Test Me, Test "Me]`
`Error: "Unknown escaped sequence in string" during evaluation  at (1, 1)`

### Minimal Example to Reproduce Behavior
eval> `"<\u2022>"`
eval> `"<\U1F534>"`

The attached patch (against 6.0.0) fixes the problem, adds support for ‘\UXXXXXX’ (UTF-32) escapes, creates less object code & is faster.

[chai_UTF_escape.diff.txt](https://github.com/ChaiScript/ChaiScript/files/1750098/chai_UTF_escape.diff.txt)

BTW String literals appear to be missing from cheatsheet.md - no mention of encoding, quoting or escaping.  Also I’m not sure I understand the `"…${<var-name>}…"` syntax i.e. when does substitution  occur and what are the scope rules for `var-name`?

**Comment by lefticus** [comment]
I've merged in all of the unicode changes that make it 100% consistent (as far as I can tell) with C++'s handling of unicode.
