### ISSUE TITLE
Add option to skip tests in cmake

### ISSUE THREAD

**Issue by hhirsch** [ChaiScript/ChaiScript#419]
Currently when I add ChaiScript to my project as a submodule all tests are run automatically.
While I did notice options to run light tests I think many users will profit from an option to skip tests compleately.

**Comment by lefticus** [comment]
Simply set `-DBUILD_TESTING:BOOL=false` when you configure it

**Comment by hhirsch** [comment]
Thank you. Worked like a charm.
