### ISSUE TITLE
Register constructor as static function with parameters?

### ISSUE THREAD

**Issue by acki-m** [ChaiScript/ChaiScript#428]
I found following example code:
```
void hello_constructor(chaiscript::Boxed_Value & o)
{
     std::cout << "Hello Constructor" << std::endl;
}

chaiscript::ChaiScript chai;

chai.add(chaiscript::Proxy_Function(new chaiscript::dispatch::detail::Dynamic_Object_Constructor("TestType", chaiscript::fun(&hello_constructor))), "TestType");
```

This works. However, how can I register a function, which takes also an argument?
And furthermore, how does this function `hello_constructor` return anything?

I would expect, it works like this:
```
TestType hello_constructor(int value)
{
     return TestType(value);
}

chaiscript::ChaiScript chai;

chai.add(chaiscript::Proxy_Function(new chaiscript::dispatch::detail::Dynamic_Object_Constructor("TestType", chaiscript::fun(&hello_constructor))), "TestType");
```
However, this result in a runtime error.

1. Is there a way to register a static function?
2. You should add static assert, that this does not work (by checking the argument type or so).

**Comment by lefticus** [comment]
I don't know why you are using `Dynamic_Object_Constructor` at all. This is a type meant for internal use only (as you can see by the `detail` namespace).

If you do the simple thing then everything should work as expected:

```cpp
TestType hello_constructor(int value)
{
     return TestType(value);
}

chaiscript::ChaiScript chai;

chai.add(chaiscript::fun(&hello_constructor), "hell_constructor");
```
