### ISSUE TITLE
how to return boxed_value from c++

### ISSUE THREAD

**Issue by chacent** [ChaiScript/ChaiScript#431]
i want a function that return boxed_value which mean i do not know the type on compile time。
on other word,the value returned is variant.
how could i do?

**Comment by RobLoach** [comment]
`auto`? It attempts to convert the type to whatever you specify. It is usually good to add any of your own types as convertion methods:
https://github.com/ChaiScript/ChaiScript/blob/develop/cheatsheet.md#adding-type-conversions

I've also converted back and forth through JSON before.

**Comment by lefticus** [comment]
did you try simply returning `chaiscript::boxed_value`? This is how much of the internals of ChaiScript work:

```cpp
// from C++ land 
chaiscript::Boxed_Value get_bv() {
  return chaiscript::val(15);
}

chai.add(chaiscript::fun(&get_bv), "get_bv");
```

or 

```cpp
chaiscript::Boxed_Value bv = chai.eval("somefunctioncall()");

try {
  // test at runtime to see if an int was returned.
  chai.boxed_cast<int>(bv); // was an int
} catch (const chaiscript::bad_boxed_cast &) {
  // it was not an int
}
```

There are other similar options as well.

-Jason
