### ISSUE TITLE
Inconsistent behavior with multiple type conversions

### ISSUE THREAD

**Issue by Gollum999** [ChaiScript/ChaiScript#433]
* Compiler Used: Visual Studio 2017 (v15.5.3, CL v19.12.25834)
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): x64
 

### Expected Behavior 
If multiple valid type conversions are provided, do one of:

1. Fail to compile
2. Always apply the first conversion specified (or last, as long as it is consistent)
3. Try conversions in order, falling to the next conversion in line if the current conversion would cause an eval_error.  (This would probably have subtle performance implications, so I'd be hesitant to add this behavior.)

### Actual Behavior 
If multiple valid type conversions are specified, one conversion is chosen randomly.  Which conversion will be applied is consistent within a single run of the application, but is inconsistent between different runs.

This might be related to #391, though my example doesn't care about `shared_ptr`s or base classes.

### Minimal Example to Reproduce Behavior
```
#include <iostream>
#include <chaiscript/chaiscript.hpp>

namespace chai = chaiscript;

struct Foo {
    int x = 123;
};

int main()
{
    chai::ChaiScript engine;

    engine.add(chai::type_conversion<int, Foo>([](int x) {
        std::cout << "Foo type conversion 1\n";
        return Foo{x};
    }));
    engine.add(chai::type_conversion<int, Foo>([](int x) {
        std::cout << "Foo type conversion 2\n";
        return Foo{x};
    }));
    engine.add(chai::type_conversion<int, Foo>([](int x) {
        std::cout << "Foo type conversion 3\n";
        return Foo{x};
    }));

    engine.add(chai::fun([](const Foo& foo) {
        std::cout << "Foo: " << foo.x << "\n";
    }), "takes_foo");

    engine.eval("takes_foo(5)");
    return 0;
}
```
```
$ for i in {0..10}; do ../Debug/ChaiScriptBug.exe; done
Foo type conversion 1
Foo: 5
Foo type conversion 1
Foo: 5
Foo type conversion 3
Foo: 5
Foo type conversion 1
Foo: 5
Foo type conversion 2
Foo: 5
Foo type conversion 1
Foo: 5
Foo type conversion 1
Foo: 5
Foo type conversion 1
Foo: 5
Foo type conversion 3
Foo: 5
Foo type conversion 1
Foo: 5
Foo type conversion 1
Foo: 5
```

**Comment by AlekMosingiewicz** [comment]
I've just tried to tackle the problem.

**Comment by AlekMosingiewicz** [comment]
Tests are failing, but it's probably a problem with the CI pipeline - all the tests have passed on my system. I've reported the issue.

**Comment by lefticus** [comment]
@AlekMosingiewicz I see two ways forward: move your patch to be on the release-6.x branch and test there, or updating of travis and appveyor configurations.

Are you interested in working on the travis and appveyor configs? The help would be most appreciated.

re #454

**Comment by AlekMosingiewicz** [comment]
I lack experience in this field, but then again, this would be opportunity to gain it.

I'd also be grateful if you reviewed my PR!

**Comment by lefticus** [comment]
I'm closing this with #453
