### ISSUE TITLE
Tests fail on Visual Studio 2017

### ISSUE THREAD

**Issue by AlekMosingiewicz** [ChaiScript/ChaiScript#434]
* Compiler Used: Visual Studio 2017
 * Operating System: Windows 10
 * Architecture: 64bit

### Expected Behavior 
Tests pass while running on Visual Studio 2017

### Actual Behavior 
Tests fail whenever environment variables, passed via CMake, are required. 

### Minimal Example to Reproduce Behavior
Run the tests using Visual Studio 2017 Community Edition.

The problem seems to be related to the fact compiler ignores parameters passed to tests via CMake.

**Comment by lefticus** [comment]
I've never seen this specific problem you are having, as all of the tests require environment variables. However, all tests are green on AppVeyor now, which was due to a new cmake version breaking things. I'm closing this issue now.
