### ISSUE TITLE
cannot compile with clang and --std=c++1z

### ISSUE THREAD

**Issue by AlexandreFoley** [ChaiScript/ChaiScript#435]
* Compiler Used: mp-clang-4.0 
 * Operating System: OSX 10.12.6
 * Architecture (ARM/x86/32bit/64bit/etc): intel 64bits
 
I am unable to compile ChaiScript-6.0.0 using clang and -std=c++1z, It compile fine when using c++14.
I tried apple-clang 9 with the same issue.
I saw a similar (closed) issue with gcc, which is what prompted me to change the standard back to 14 when testing compilation with clang.

### Expected Behavior 
Compiles.
### Actual Behavior 
Fail to compile.

### Minimal Example to Reproduce Behavior

main.cpp:

`#include <chaiscript/chaiscript.hpp>

std::string helloWorld(const std::string &t_name) {
  return "Hello " + t_name + "!";
}

int main() {
  chaiscript::ChaiScript chai;
  chai.add(chaiscript::fun(&helloWorld), "helloWorld");

  chai.eval(R"(
    puts(helloWorld("Bob"));
  )");
}`

and tried to compile with 

`clang++  -IChaiScript-6.0.0/include  -std=c++1z -o 'main.cpp.o' -c main.cpp`

It fails with a huge mess of template error messages.

[error.txt](https://github.com/ChaiScript/ChaiScript/files/1957855/error.txt)

**Comment by lefticus** [comment]
You must use current develop branch for C++17 support.

**Comment by AlexandreFoley** [comment]
Ah, thanks.
