### ISSUE TITLE
Script files with UTF-8 BOM aren't executed

### ISSUE THREAD

**Issue by MarioLiebisch** [ChaiScript/ChaiScript#436]
While ChaiScript supports UTF-8 sequences in strings it seems that files encoded in UTF-8 with a BOM at the start will fail silently – this actually drove me nuts until I actively stepped through.

* If the user provided input is a file (i.e. as parameter to `use()` or `eval_file()`), the BOM should be skipped.
* If the user provided input as a string, the BOM should probably trigger "Unparsed Input".

As of right now (current `master` branch), `Statements()` will not match the first character of the BOM at the start to any known statement (which is correct and for obvious reasons) and as such just return `false` (which is then interpreted as a no-op).

Minimal example:

```cpp
#include <iostream>
#include "chaiscript/chaiscript.hpp"

int main() {
  chaiscript::ChaiScript chai;

  chai.add(chaiscript::fun([](const std::string &text) { std::cout << text; }), "print");

  // The following expression is skipped rather than
  // causing an "Unparsed Input" exception or skipping
  // the BOM (in case of a file).
  chai.eval("\xef\xbb\xbfprint(\"Hello World!\");");

  return 0;
}
```

**Comment by AlekMosingiewicz** [comment]
I've added a fix for UTF-8, but perhaps I should also add fix for other BOMs?

**Comment by MarioLiebisch** [comment]
I'm not really sure. Two things here:

* Only skip BOMs that actually mark encodings the parser is able to handle (haven't tested this).
* As mentioned, the parser probably shouldn't skip a BOM at the start of a user provided script/string.

**Comment by MarioLiebisch** [comment]
Something I completely forgot about this. In theory one could use the codecvt header to read all the different encodings properly with little to no overhead (i.e. only when such BOM/header is found). However I've heard it's basically deprecated in C++17 with no replacement yet.

@lefticus I'd vote on simply accepting the PR for now. While it's no perfect solution it's still an improvement, especially considering UTF-8 with BOM is rather prominent on Windows (e.g. for me Notepad++ defaults to it). You could still look into the parser silently skipping *any* file/input that starts with something that's not a statement to ChaiScript (like non-ANSI characters). It should trigger "unparsed input" after all.

**Comment by AlekMosingiewicz** [comment]
I've started working on improvements @MarioLiebisch suggested. I've added inlining the BOM in test and making the BOM sequence at the beginning of input throw exception; however it'd still throw exception when reading from file, and while I've an idea of how to handle it it'd take a while to implement. So perhaps I'd leave the solution I already pushed to the branch so the scripts with BOM are at least executed, or revert the changes I've made and only add inlining BOM in the test.

**Comment by MarioLiebisch** [comment]
I'd just readjust the stream position after opening. This should barely be noticeable in any regular use case.

For (internal) work stuff I typically do a very minimalistic check like this (we only use UTF-8 BOM or no BOM):

    if (stream.peek() == 0xef) // BOM
        stream.seekg(3);

One could of course read up to 3 characters and compare those as well, resetting the stream position accordingly.

**Comment by AlekMosingiewicz** [comment]
I pushed new changes to my branch. These include actually checking if user-provided code starts with BOM ( in this case I throw exception ) and skipping BOM when it's found in the beginning of external file.

**Comment by MarioLiebisch** [comment]
Certainly better, but I'd expect an error on any garbage input. So basically passing a script like `\xefHello` and `H\xefllo` should both trigger `Unparsed Input`. This just checks for the UTF-8 BOM, so first example should still just do nothing I think – haven't tried your changes, though.

The more I think about the more I this error should in any case actually be more like "Unexpected Character" rather than "Unparsed Input".

**Comment by MarioLiebisch** [comment]
Not necessarily. I haven't looked too deep into the parser architecture, but I'd assume all we need is an additional check for `has_more()` in [chaiscript_parser.hpp, line 2610](https://github.com/ChaiScript/ChaiScript/blob/develop/include/chaiscript/language/chaiscript_parser.hpp#L2610). Just compare this to how line 2605 verifies the script finished properly.

**Comment by AlekMosingiewicz** [comment]
I'm now throwing the "Illegal character" exception in `SkipWS()` method, as it's called in virtually every method that parses the input. Currently it's thrown for every character encountered that is above the standard ASCII range, but perhaps I should set an upper limit for this character range, as I don't know how it will behave if it encounters a unicode character.

**Comment by AlekMosingiewicz** [comment]
I'd appreciate any feedback on my recent changes...

**Comment by MarioLiebisch** [comment]
Completely missed the notification. Added a few comments.

**Comment by AlekMosingiewicz** [comment]
I've introduced the changes; please take another look.

**Comment by AlekMosingiewicz** [comment]
Ok, so I've added those three test cases - the case with BOM in beginning of file was already covered by unit test - and refactored the code. Please take a look.

**Comment by MarioLiebisch** [comment]
Added one last remark regarding the header check. Besides that, looks fine to me.

**Comment by AlekMosingiewicz** [comment]
I've introduced all the changes, but now the tests fail on Clang Xcode 8 with no environment variables.

**Comment by MarioLiebisch** [comment]
Yep, exactly. One could even add a fourth byte, still read 3 bytes, and then compare the two strings as a 32 bit number, although I guess that's premature optimization on a different level. ;)

**Comment by AlekMosingiewicz** [comment]
Ok, fixed the implicit conversion warning. I just switched to Windows and VC++, will try to recreate the pipeline problem on my machine.

**Comment by AlekMosingiewicz** [comment]
I can't replicate the issue on my Visual Studio.
