### ISSUE TITLE
`use()` masking any `file_not_found_error` happening; potentially running unexpected scripts

### ISSUE THREAD

**Issue by MarioLiebisch** [ChaiScript/ChaiScript#437]
*Maybe we're not supposed to do this, but haven't seen any remarks regarding this.*

When using nested calls to `use()`, failed calls will be masked by the outer call, which will report its own file to be missing, even if it has been loaded, parsed, and executed so far (scenario 1). This could even cause execution of multiple files with the same name (in different locations), just due to some embedded dependency failing (scenario 2).

`use()` should probably re-throw any inner `file_not_found_error` exception, if it's with a different file name rather than continuing and trying the next given path.

## Scenario 1
Create a text file `script.chai` and add a single line: `use("something");`

```cpp
#include <iostream>
#include "chaiscript/chaiscript.hpp"

int main() {
  chaiscript::ChaiScript chai;
  try {
    chai.use("script.chai");
  }
  catch (const std::exception &ex) {
    std::cout << ex.what() << "\n";
  }
  return 0;
}
```

**Actual Result**
* ChaiScript executes `script.chai` and reports `script.chai` as not found.

**Expected Result**
* ChaiScript executes `script.chai` and reports `something` as not found.

## Scenario 2
* Create a text file `./A/script.chai` and add a single line: `print("Hello from A!"); use("something");`
* Create a text file `./B/script.chai` and add a single line: `print("Hello from B!");`

```cpp
#include <iostream>
#include "chaiscript/chaiscript.hpp"

int main() {
  chaiscript::ChaiScript chai({}, {"./A/", "./B/"});

  chai.add(chaiscript::fun([](const std::string &text) { std::cout << text; }), "print");

  try {
    chai.use("script.chai");
  }
  catch (const std::exception &ex) {
    std::cout << ex.what() << "\n";
  }

  return 0;
}
```

**Actual Result**
* ChaiScript executes `./A/script.chai`, followed by `./B/script.chai`, printing `Hello from A!Hello from B!`, and not reporting any issue.

**Expected Result**
* ChaiScript executes `./A/script.chai` and reports `something` as not found.

**Comment by MarioLiebisch** [comment]
Yes, a missing file on its own level is the correct behavior. The problem is when the "file not found" happens a layer deeper in some nested file or call. In scenario 2, the script within `A` should trigger an error about `something` not being found. It shouldn't silently jump to `B` after executing at least parts of `A`.

**Comment by lefticus** [comment]
I think I can fix this relatively easily. I'll look into it shortly.

**Comment by AlekMosingiewicz** [comment]
You could leave it to me as well - I found where it's handled, so the fix should be easy. I'd only have to write tests for this case.
