### ISSUE TITLE
Bash-like features

### ISSUE THREAD

**Issue by marek094** [ChaiScript/ChaiScript#448]
Hello, 
is there any Bash/Perl-like command line api for chaiscript?
For example unix file system support? Or 'os.execute' in Lua?

Thx

**Comment by lefticus** [comment]
Please clarify what you mean. Are you interested in calling other executables from within ChaiScript?

This could be trivially added in your own code by just adding `system` to your ChaiScript environment.

**Comment by RobLoach** [comment]
Feel free to create a ChaiScript module that exposes os/bash-like methods. If you submit it to https://github.com/ChaiScript/ChaiScript_extras , I'd be willing to give it a review.

In the mean time, feel free to create an issue over there. Going to close this for now. Thanks!
