### ISSUE TITLE
Ambiguous function calls, when adding a class with operator[]

### ISSUE THREAD

**Issue by vocaviking** [ChaiScript/ChaiScript#449]
* Compiler Used:
MSVC 15.7.4
 * Operating System:
Windows

### Expected Behavior 
I have written a custom class, which for performance reasons has two versions of the element `operator[]`. I would like to add this class to chaiscript without disabling one of the operator versions.
### Actual Behavior 
The compiler tells me (rightly), that I have an ambiguous function call:
```
1>error C2668: 'chaiscript::fun': ambiguous call to overloaded function
1>chaiscript\dispatchkit\register_function.hpp(72): note: could be 'chaiscript::Proxy_Function 1>chaiscript::fun<int&,test,int>(Ret (__thiscall test::* )(int))'
1>        with
1>        [
1>            Ret=int &
1>        ]
1>chaiscript\dispatchkit\register_function.hpp(63): note: or  'chaiscript::Proxy_Function chaiscript::fun<const int&,test,int>(Ret (__thiscall test::* )(int) const)'
1>        with
1>        [
1>            Ret=const int &
1>        ]
```
### Minimal Example to Reproduce Behavior
```c++
#include <chaiscript/chaiscript.hpp>

struct test
{
  auto& operator[](int i) { return i; }
  const auto& operator[](int i) const { return i; }
};

int main(int argc, char* argv[]) {
  chaiscript::ChaiScript chai;
  chai.add(chaiscript::user_type(test()), "test");
  chai.add(chaiscript::fun(&test::operator[]), "[]");
}
```
### Discussion
This is not actually a problem with chaiscript itself, but with the overloading of c++ functions. One mitigation is to use a lambda:
```c++
  chai.add(chaiscript::fun(

  [](test& e, const int& i) {
    return e[i];
  }

  ),"at");
```
However, I would rather use the `[]` syntax. Does anyone have a suggestion on how to achieve this?

**Comment by lefticus** [comment]
This is not a bug or issue in ChaiScript, this is how C++ works. It's impossible to pass a pointer to an overloaded function. Using a lambda is nice and clean way to do it. the other option is to use `static_cast<>` to force C++ to know which version you are talking about.
