### ISSUE TITLE
Feature request: Custom module resolution

### ISSUE THREAD

**Issue by codehz** [ChaiScript/ChaiScript#450]
(I skipped the template because it isn't a issue report)
It will be nice to provide a option to customize the suffix and prefix of the module resolution, or just provide a callback to resolve the path of the module and `use`.

**Comment by RobLoach** [comment]
Depends on how the file system is loaded. I've used PhysFS to abstract the file system loading in [ChaiLove](https://github.com/libretro/libretro-chailove). The result is being able to use `require("myfile")` to load a module.

In ChaiScript on the C++ front, you can register your own require function to change its behavior. What did you have in mind?

**Comment by codehz** [comment]
custom filesystem seems a good idea..
