### ISSUE TITLE
CI failing after migration to C++17

### ISSUE THREAD

**Issue by AlekMosingiewicz** [ChaiScript/ChaiScript#454]
I've created a pull request addressing #433 , after running all the tests on my MinGW compiler. It turned out that the tests failed to compile on both AppVeyor and Travis. In case of GCC it was a compiler option, so there's definitely something broken in the CI configuration.

**Comment by lefticus** [comment]
We probably just want to remove VS14 from appveyor.yml. I think we're still a little ways from getting chaiscript to compile in VS15, but we'll leave it there.

For travis we'll need to add a gcc 7 or 8? and remove the others. We'd want at least one build remaining that reports coverage back.

I have *no idea* what the status is for MacOS https://travis-ci.org/ChaiScript/ChaiScript/builds/415599318?utm_source=github_status&utm_medium=notification

Looks like we could move to Xcode 9.4, but Apple really doesn't tell us what compiler that uses, so I don't know if it would support what we need for C++17 https://docs.travis-ci.com/user/reference/osx#os-x-version

**Comment by AlekMosingiewicz** [comment]
According to Travis logs it's the case of compiler options and missing standard libraries, so it should be definitely the problem with old compilers. I'll try to tackle it when I'm back home.

**Comment by AlekMosingiewicz** [comment]
@lefticus My proposition as far as Travis CI is concerned would be to temporarily disable the OSX build, at least until Travis has version that supports variant. When Travis is fixed then I'll take a look at Appveyor.

**Comment by AlekMosingiewicz** [comment]
@lefticus I cleaned up my PR as much as I could and left some comments in it. I believe we should try and close this issue somehow.

**Comment by RobLoach** [comment]
Nice work getting Travis to work! Should we tackle Appveyor in another issue?
