### ISSUE TITLE
Bitwise operators

### ISSUE THREAD

**Issue by Brandantl** [ChaiScript/ChaiScript#461]
* Compiler Used: MSVC
 * Operating System: Win 10
 * Architecture (ARM/x86/32bit/64bit/etc): 32
 
Are bitwise operators supported? Such as a bitwise and? I tried if (someint & someint) and it just kind of crashes. I dont see bitwise operators in the documentation or in the unit tests.

**Comment by lefticus** [comment]
Yes they are supported. The "just kind of crashes" is an explicit exception telling you that an integer cannot be converted to a boolean. ChaiScript has far fewer implicit conversions. You need to do `if ((someint & someint) != 0)`

**Comment by Brandantl** [comment]
I didn't actually review the crash it was just reported to me via a scripter. The crash was caused because my logging library I made only had a 1024 character buffer and chai errors far exceed that. Thanks!
