### ISSUE TITLE
use dynamic library functions

### ISSUE THREAD

**Issue by jaafari** [ChaiScript/ChaiScript#465]
* Compiler Used: msvc 17
 * Operating System: windows 10
 * Architecture (ARM/x86/32bit/64bit/etc):  64bit

I want to use opencv functions in chaiscript, but when I run it, program causes crash:

```
chaiscript::ChaiScript chai;
cv::Mat a = cv::imread("myImage1.png");
cv::Mat b = cv::imread("myImage2.png");
chai.add(chaiscript::user_type<cv::Mat>(), "Mat"));
chai.add(chaiscript::constructor<cv::Mat>(), "Mat"));
chai.add(chaiscript::fun(static_cast<cv::Mat (*) (const cv::Mat& e1 , const cv::Mat& e2)>(&cv::MatExpr::operator), "+");
chai.add(chaiscript::var(a), "A");
chai.add(chaiscript::var(b), "B");

 chai.eval<cv::Mat>("A + B"); // this line causes crash
```
is it necessary to load opencv dll in chaiscript? how?

**Comment by lefticus** [comment]
How does it crash? is it an unhandled exception? What does the exception say?

**Comment by RobLoach** [comment]
Rather than calling it dynamically, would it be possible to statically link it? Then you won't have to cross-compile opencv dll for ARM, you'd just compile it as part of your binary.

**Comment by jaafari** [comment]
```
Boxed_Value eval(const chaiscript::detail::Dispatch_State &t_e) const final
      {
        try {
          T::trace(t_e, this);
          return eval_internal(t_e);
        } catch (exception::eval_error &ee) {
          ee.call_stack.push_back(*this);
          throw;
        }
      }
```
on "return eval_internal(t_e);"
exception:
chaiscript::exception::eval_error: cannot find appropriate + operator with parameters (Mat, Mat) ... 

I cannot link it dynamically because my program is part of another project which uses dynamic opencv.

**Comment by jaafari** [comment]
I've found the problem. opencv converts cv::Mat to cv::MatExpr and  cv::MatExpr to cv::Mat implicitly, when I add their constructor, it works, thanks.
