### ISSUE TITLE
release windows issues

### ISSUE THREAD

**Issue by toutant** [ChaiScript/ChaiScript#471]
* Microsoft Visual Studio 2015 Update 3:
 *Windows 10:
 * Architecture (x86/32bit/): 
 

### Expected Behavior : Debug compiles fine.
Release : unresolved external symbol ___iob_func

### Minimal Example to Reproduce Behavior
I have WCHAR default I also include mysql library and sciter library . ( c library )
if I take out chaiscript everything compiles and works.(debug and release) when i add chaiscript and try to compile for release version i get the error 'unresolved external symbol ___iob_func'

**Comment by RobLoach** [comment]
Agreed, latest master has been buggy in VS builds...

Does 6.1.0 work? https://github.com/ChaiScript/ChaiScript/releases/tag/v6.1.0

**Comment by toutant** [comment]
I managed to put chaiscript in a dll and no problems.
: )
