### ISSUE TITLE
Capture output

### ISSUE THREAD

**Issue by tstavrianos** [ChaiScript/ChaiScript#475]
I am trying to integrate chaiscript into a GUI application and would like to wrap all functions that use stdout or stderr directly (print_string and println_string only unless I am mistaken).

How would I do this from the C++ ? (other than copying the contents of chaiscript/dispatchkit/bootstrap.hpp to my chaiscript init script and replacing the above two functions with my own).

My aim is logging and output from the script into a file and an in-app dev console for run-time debugging.

**Comment by RobLoach** [comment]
If you add your own `print` function, it'll be used by ChaiScript.

**Comment by tstavrianos** [comment]
That will fix a script using the print function (which appears to be chaiscript defined function wrapping print_string) but will not fix a script using print_string or println_string directly.

**Comment by RobLoach** [comment]
You might be able to add those functions too. I believe when a function is added, it'll opt to the last one added. I could be wrong on that though.

If you find a way to get multiple argument lists working, let me know, I've been curious myself.

**Comment by Ybalrid** [comment]
I use this method posted par jason a while ago on the forum : http://discourse.chaiscript.com/t/controlling-print-destination/177/4

I have an ImGui gui, wrapped into a class that exposes a method to push a line of text to the console buffer.
```
	//print to the console with this
	chai.add(fun([=](const std::string& str){gui_ptr->push_to_console(str);}), "handle_output");
	chai.eval("global print = fun(x) { handle_output (to_string(x)); }");
```

Then I provide a number of overload of "to_string". You probably also can define a global function for `print_string` too that would sink the text to the same handle_output.

**Comment by tstavrianos** [comment]
Thanks, that did the trick. I'll look into turning the script into a module that I can use when instantiating the engine, so that I don't have to include it with all my scripts.
