### ISSUE TITLE
Namespace clashes with nlohmann::json

### ISSUE THREAD

**Issue by reFX-Mike** [ChaiScript/ChaiScript#486]
The excellent JSON library at

https://github.com/nlohmann/json

can cause problems, because Chairscript and they use the namespace "json".

We use the nlohmann::json library a lot in our projects and occasionally also need Chaiscript, but whenever we do, we get clashes.

Would it be possible to put the the chairscript json namespace into the "chaiscript" namespace, so we can continue using "using nlohmann::json" without running intro trouble?

**Comment by lefticus** [comment]
You're right! This really should be in the `chaiscript::` namespace.
