### ISSUE TITLE
var++ expressions are not parsed and run

### ISSUE THREAD

**Issue by delahee** [ChaiScript/ChaiScript#490]
Hey,

Pretty sure this is a language feature but well... one never knows...
We now use chaiscript heavily in our next engine hot reload toolchain, it generaly works very well. 
Some minor "welcoming" oddity is "my var" ++ ( post increment )  seems to fail.

It could be generally okay to not support it but it feels strange, especially regarding the overall very high quality of the script engine.

Please feel free to close if it is not relevant.

* Compiler Used: visual studio 2017
 * Operating System: win
 * Architecture (ARM/x86/32bit/64bit/etc):  64bit
 

### Expected Behavior 
'''var o = 0;
o++;''' should compile and execute

'''for( var i = 0; i < 8; i++ )''' should compile and execute

### Actual Behavior 
fails with Incomplete prefix '++' expression

### Minimal Example to Reproduce Behavior
'''var i = 0;
i++;'''

**Comment by lefticus** [comment]
It's a "feature" in that the way the parser is written it's been too hard to add postfix increment. I've tried.

Plus the overall decision that it's very rare that you actually semantically want "increment and return the last value," and usually actually want "increment and return the new value," so it's been low priority to try and make the parser work with it.

**Comment by delahee** [comment]
Okay I ll just close to reduce noise then :) 

Thanks for your precious time ^^
