### ISSUE TITLE
Two or more script in one application

### ISSUE THREAD

**Issue by qmor** [ChaiScript/ChaiScript#508]
* Compiler Used:
MSVC 2015
 * Operating System:
Windows 8
 * Architecture (ARM/x86/32bit/64bit/etc): 
X64 

### Expected Behavior 
I need to use couple of scripts in my application which have to use some global c++ functions to have access to c++ vars or other internal application things.  Because of that i've create singletone "Script manager" which maps global functions to chai in constructor. But then i'm using another ChaiScript instance it doesnot see the fucntion registered in "Script manager" instance of ChaiScript

### Actual Behavior 
Two instances of ChaiScript can't share functions.

### Minimal Example to Reproduce Behavior
                        ChaiScript chai;
			using PlainLog = void(*)(const std::string &);
			chai.add(fun(PlainLog(&my_stdout)), "log");
			chai.eval(R"(log("Hello World"))");
			ChaiScript anotherchai;
			anotherchai.eval(R"(log("Hello World from another script"))"); //throws exception

**Comment by draghan** [comment]
I think you have to register the `log` function in the second instance of `ChaiScript` as well:

```
ChaiScript chai;
using PlainLog = void(*)(const std::string &);
chai.add(fun(PlainLog(&my_stdout)), "log");
chai.eval(R"(log("Hello World"))");
ChaiScript anotherchai;
anotherchai.add(fun(PlainLog(&my_stdout)), "log");
anotherchai.eval(R"(log("Hello World from another script"))"); //throws exception
```

The `anotherchai` object is not aware of the presence of the `log` function registered in the `chai` object.

**Comment by RobLoach** [comment]
What Drag said :+1:
