### ISSUE TITLE
to_int Conversion

### ISSUE THREAD

**Issue by joshmcf** [ChaiScript/ChaiScript#538]
* Compiler Used: MSVC
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): 64bit
 

### Expected Behavior 
In Chaiscript:
`to_int("2252400000")` returns int64 with value of `2252400000`
### Actual Behavior 
returns incorrect value of `2147483647`
### Minimal Example to Reproduce Behavior
As above.
Also try evaluating `to_string(to_int("2252400000"))` to further prove this.

I suggest this is an overflow issue with the to_int function.

**Comment by BerndAmend** [comment]
The function to_int() returns an int (https://github.com/ChaiScript/ChaiScript/blob/develop/include/chaiscript/dispatchkit/bootstrap.hpp#L462), to get the int64 value you have to call to_int64_t().
