### ISSUE TITLE
work only C++ functions with constants

### ISSUE THREAD

**Issue by sr-tream** [ChaiScript/ChaiScript#546]
* Compiler Used: MinGW 10
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): x86
 

### Expected Behavior 
Execute Chai code
### Actual Behavior 
Variables and functions does not work. Work any functions binded from C++ and called with consts
### Minimal Example to Reproduce Behavior
```c++
chaiscript::ChaiScript chai;
chai.add( chaiscript::fun<std::function<void( std::string )>>(
				  []( std::string msg ) { MessageBoxA( 0, msg.data(), 0, 0 ); } ),
			  "msg_box" );
chai.eval("msg_box(\"asd\")"); // work
chai.eval("var a = "asd"\
msg_box(a)"); // not work
```

**Comment by RobLoach** [comment]
What you're proposing is the same as....

```
var a = "asd"msg_box(a)
```

You'll need a `\n` there.

**Comment by sr-tream** [comment]
> You'll need a \n there.

It's inserted automaticly with new line after `\`
