### ISSUE TITLE
Stack_Vector

### ISSUE THREAD

**Issue by balint-luko** [ChaiScript/ChaiScript#547]
* Compiler Used: -
 * Operating System: -
 * Architecture (ARM/x86/32bit/64bit/etc): -

### Expected Behavior 
When browsing the source code, I noticed a possible bug in "include/chaiscript/utility/stack_vector.hpp":
In function `pop_back()` the variable `m_size` is post-decremented, but I think it should be pre-decremented.

I found the error at this location:
https://codedocs.xyz/ChaiScript/ChaiScript/stack__vector_8hpp_source.html

**Comment by RobLoach** [comment]
Good find!
