### ISSUE TITLE
CALL FUNCTION DEFINED IN CHAISCRIPT

### ISSUE THREAD

**Issue by tixvage** [ChaiScript/ChaiScript#564]
* Compiler Used:g++ 11.1.0
 * Operating System:arch linux
 * Architecture (ARM/x86/32bit/64bit/etc):64 bit 
![Screenshot_20210529_213916](https://user-images.githubusercontent.com/73782477/120081561-ebf9b400-c0c6-11eb-91dd-2f0eee8cc31f.png)

i want to call func in chaiscript like in this photo how can i do that?

**Comment by RobLoach** [comment]
There's a great tutorial series over at:
https://mightynotes.wordpress.com/2017/04/10/chaiscript-tutorial-5-calling-chaiscript-functions-from-c-and-vise-versa/
