### ISSUE TITLE
Example / How to pass Map() to C++ function

### ISSUE THREAD

**Issue by mulderp** [ChaiScript/ChaiScript#576]
### Expected Behavior 

Using in a chaiscript:

     var lib_vars = ["a": "foo", "b": "bar"]; 

I am trying to pass the values to a C++ function:

    pass_vars(lib_vars);

However, using std::map<string, string> I get: 

    Error: "Error calling function 'pass_vars'" With parameters: (Map)

Not sure what the correct syntax is to work with the map values in C++.

**Comment by BerndAmend** [comment]
You need to register the type std::map<std::string, std::string>.
`chaiscript::bootstrap::standard_library::map_type<std::map<std::string, std::string>>("StringMap", *m);
  m->add(chaiscript::map_conversion<std::map<std::string, std::string>>());`

**Comment by mulderp** [comment]
Thanks, this works:

```
  chaiscript::ChaiScript chai;
  chaiscript::bootstrap::standard_library::map_type<std::map<std::string, std::string>>("StringMap");
  chai.add(chaiscript::map_conversion<std::map<std::string, std::string>>());
  std::function<void(map<string, string> )> wrp_print_map = print_map;
  chai.add(chaiscript::fun(wrp_print_map), "print_map");
```

Chaiscript:

```
  var m = [ "a": "1", 
            "b": "2", 
            "c": "3" ];
  print_map(m);
```
