### ISSUE TITLE
bad_box_cast when casting eval to double

### ISSUE THREAD

**Issue by siladrenja** [ChaiScript/ChaiScript#585]
* Compiler Used: Visual studio 2017
 * Operating System: win10
 * Architecture (ARM/x86/32bit/64bit/etc): x86 64bit
 

### Expected Behavior 
return a double
### Actual Behavior 
throws a bad_boxed_cast exception
### Minimal Example to Reproduce Behavior

#include <iostream>
#include <chaiscript/chaiscript.hpp>

double CheckIfTrue(int input, std::string* equation, chaiscript::ChaiScript& chai) {
	
	auto  result = chai.eval(*equation);
	return chai.boxed_cast<double>(result);
}

int main() {
	chaiscript::ChaiScript chai;
	std::string actions[] = { "+","-","*","/","*0", "*10+"};
	std::string equation;
	int input;

	std::cin >> equation;

	std::cout << CheckIfTrue(0, &equation, chai) << std::endl;

	std::cout << "test2";
	
	return 0;
}

**Comment by totalgee** [comment]
What input are you giving your program? In general, you should try/catch around the eval, because the input may not be a valid ChaiScript expression...

**Comment by siladrenja** [comment]
2+2 was the first input I gave it, but I also tried 3/4, 1/2 etc. Same results. 

If I cast it to integer all of those inputs give a valid result (in case of a decimal number it just gives me biggest whole number as if I cast float to int normaly)

**Comment by totalgee** [comment]
What about if you use 2.0+3.0?

Also you may need to register explicit type conversion support, e.g.:

```
chai.add(type_conversion<int, double>());
```

**Comment by siladrenja** [comment]
2.0+3.0 works, thx.

is there any way to make it work without having to add .0?

**Comment by totalgee** [comment]
See my comment about adding type conversions. In particular, from int to double in your case.

**Comment by siladrenja** [comment]
oh, ok, thx.
