### ISSUE TITLE
badboxedcast when using absolutes

### ISSUE THREAD

**Issue by siladrenja** [ChaiScript/ChaiScript#586]
* Compiler Used: Visual studio 2017
 * Operating System: Windows 10
 * Architecture (ARM/x86/32bit/64bit/etc): x86 64bit
 

### Expected Behavior 
return the absolute value of a number
### Actual Behavior 
Unhandled exception at 0x7772B5B2 in Project10.exe: Microsoft C++ exception: chaiscript::exception::bad_boxed_dynamic_cast at memory location 0x00ABE3A0. occurred

actual line that throws the exception:
throw exception::bad_boxed_dynamic_cast(to.get_type_info(), *from.bare_type_info(), "No known conversion");

### Minimal Example to Reproduce Behavior
        chaiscript::ChaiScript chai;
        chai.add(chaiscript::type_conversion<int, double>());
        std::string equation;
	std::cin >> equation;

	std::cout << chai.eval<double>(equation);

I tried both |-1| and  absolute(-1) (2nd one gives a different error that it can't find object, which I understand)

**Comment by totalgee** [comment]
The `|-1|` notation is definitely not supported by ChaiScript (or most programming languages I know of). As for `abs()`, you'd need to expose it yourself. This can be done easily using the math helpers, see the instructions here:

https://github.com/ChaiScript/ChaiScript_Extras#math
