### ISSUE TITLE
How to get the function pointer from std::function?

### ISSUE THREAD

**Issue by aliule2020** [ChaiScript/ChaiScript#595]
//realtype is double, svec is std::vector<double>
 auto f = chai.eval<function<realtype(realtype t, svec x, svec c) > > ("func");
//then I want to get the function pointer,but failed
cout << (*f.target<realtype(*)(realtype, svec, svec)>())(t, x, c) << endl; //failed

How to get the function pointer?

**Comment by totalgee** [comment]
Is what you want really to "get the function pointer" for some reason, or just call the function?

Assuming `t`, `x` and `c` are of the right types, you should be able to just use the call operator: `f(t, x, c)`.

**Comment by aliule2020** [comment]
Thank you.
